#pragma once

#include <string>
#include <string_view>

namespace magmaan::parse::detail {
// Rejection classes share language contracts, not a generic fallback.
inline std::string mplus_rejection_contract(std::string_view rule) {
  if (rule == "LX01") return "; Mplus requires command heads on new lines and semicolon-terminated options; magmaan rejects this because an incomplete or repeated command has no unambiguous input meaning; instead, write DATA, VARIABLE and MODEL once, with colon heads and semicolon terminators.";
  if (rule == "LX02") return "; Mplus truncates input records at column 90; magmaan rejects this because truncation can change the model; instead, wrap statements before column 91.";
  if (rule == "LX03") return "; Mplus resolves unique command/option prefixes of at least four letters and exact documented setting stems; magmaan rejects this because unknown or ambiguous tokens cannot be imported; instead, write a complete command/option name and an exact setting.";
  if (rule == "LX05") return "; Mplus allows delimited comments but drops preceding code when a block closes on another line; magmaan cannot silently discard model code; instead, close the block on its opening line or put its opening delimiter on a separate line.";
  if (rule == "NM01") return "; Mplus uses letter-led names containing letters, digits and underscores; magmaan rejects this because invalid names cannot identify model variables; instead, rename the variable or factor with a letter-led name.";
  if (rule == "NM02") return "; Mplus expands NAMES ranges by shared numeric or letter suffix; magmaan rejects malformed, duplicate or oversized schemas and ambiguous renaming; instead, list distinct variable names explicitly, or use a bounded matching-suffix range.";
  if (rule == "NM03") return "; Mplus selects observed ranges in NAMES or USEVARIABLES order; magmaan rejects this because unknown, repeated or reversed endpoints cannot select the intended columns; instead, list each analysis name once in forward schema order; compute DEFINE variables in R.";
  if (rule == "NM04") return "; Mplus selects latent ranges in factor-definition order, separately from observed names; magmaan rejects this because mixed or reversed ranges cannot preserve that ordering; instead, list observed and latent names separately in their definition order.";
  if (rule == "CL02") return "; Mplus reads a separate FILE, with quoted paths when they contain blanks; magmaan needs a resolvable path for each data block; instead, write FILE = path or FILE (group) = path, quoting paths with blanks.";
  if (rule == "CL03") return "; Mplus uses a consistent data TYPE, positive counts and one LISTWISE setting; magmaan rejects this because inconsistent data metadata cannot define the sample moments; instead, write one INDIVIDUAL or summary matrix type, matching positive NOBSERVATIONS counts and LISTWISE = ON or OFF.";
  if (rule == "CL04") return "; Mplus uses SWMATRIX for two-level WLS and MONTECARLO/IMPUTATION for multiple datasets; magmaan rejects this because these data families are outside project/grammar/mplus.md Not planned; instead, supply one INDIVIDUAL dataset or a supported covariance/correlation summary.";
  if (rule == "CL06") return "; Mplus transforms data through qualified DATA commands; magmaan does not execute data transformations (project/grammar/mplus.md Not planned); instead, perform the transformation in R and supply the resulting FILE and NAMES.";
  if (rule == "CL10") return "; Mplus uses CATEGORICAL for binary/ordinal outcomes and category-set modifiers for full-information item models; magmaan imports plain binary/ordinal lists, not those link models (project/grammar/mplus.md Not planned); instead, write a plain list of distinct CATEGORICAL outcome names with two through ten categories.";
  if (rule == "CL13") return "; Mplus selects cases with USEOBSERVATIONS or SUBPOPULATION; magmaan cannot ignore sample selection; the subset is parked in project/backlog/speculative.md; instead, select the cases in R before fitting and remove the selection option.";
  if (rule == "CL14") return "; Mplus defines count, nominal, censored, survival or time-series/random-time outcome families with these options; magmaan rejects this because those families are outside project/grammar/mplus.md Not planned; instead, supply a linear continuous or binary/ordinal SEM; retain other outcome families in Mplus.";
  if (rule == "CL15") return "; Mplus uses these options for auxiliary-variable methods, data-dependent constraints, designs, weights, mixtures or multilevel models; magmaan rejects this because these families are outside project/grammar/mplus.md Not planned; instead, supply an unweighted single-level linear SEM without these options; retain the original family in Mplus.";
  if (rule == "CL16") return "; Mplus transforms or creates variables with DEFINE; magmaan cannot ignore data transformations; the subset is parked in project/backlog/speculative.md; instead, compute the transformations in R, update NAMES and remove DEFINE.";
  if (rule == "CL17") return "; Mplus uses TYPE for descriptives, random effects, survey, mixture, multilevel or EFA analysis; magmaan rejects this because these families are outside project/grammar/mplus.md Not planned; BASIC has no explicit SEM; instead, write TYPE = GENERAL with an explicit linear MODEL, or retain the requested family in Mplus.";
  if (rule == "CL18") return "; Mplus uses BAYES/MUML for Bayesian/multilevel models and categorical ML for full-information links and numerical integration; magmaan rejects this because these estimator families are outside project/grammar/mplus.md Not planned; instead, use a continuous linear SEM or an all-ordinal weighted-least-squares input; retain full-information links in Mplus.";
  if (rule == "CL20") return "; Mplus expands CONFIGURAL, METRIC or SCALAR into invariance models; magmaan needs one supported invariance setting; instead, write exactly one CONFIGURAL, METRIC or SCALAR setting with declared groups.";
  if (rule == "CL21") return "; Mplus uses ALLFREE/ALIGNMENT for mixture or alignment models; magmaan rejects this because alignment is outside project/grammar/mplus.md Not planned; instead, write one ordinary grouped linear MODEL or retain alignment in Mplus.";
  if (rule == "CL22") return "; Mplus uses DELTA/THETA for limited-information categorical models and other settings for mixture/link models; magmaan rejects this because those other families are outside project/grammar/mplus.md Not planned; instead, write one PARAMETERIZATION = DELTA or THETA.";
  if (rule == "CL23") return "; Mplus uses LINK, non-normal DISTRIBUTION or correlation-structure MATRIX settings for different analysis families; magmaan rejects this because these families are outside project/grammar/mplus.md Not planned; instead, supply a covariance-structure linear SEM with DISTRIBUTION = NORMAL and MATRIX = COVARIANCE.";
  if (rule == "CL24") return "; Mplus uses rotation and related controls for EFA/ESEM, survey replication or survival models; magmaan rejects this because those families are outside project/grammar/mplus.md Not planned; instead, write explicit ordinary BY factors, or retain the requested analysis family in Mplus.";
  if (rule == "CL26") return "; Mplus uses labelled MODEL sections for declared groups; magmaan cannot resolve a group without its schema; instead, declare explicit GROUPING code/label pairs or labelled FILE groups before using MODEL label.";
  if (rule == "CL29") return "; Mplus uses MONTECARLO and simulation MODEL commands to generate populations, coverage or missingness models; magmaan rejects this because simulation input is outside project/grammar/mplus.md Not planned; instead, generate data separately and write an ordinary analysis MODEL.";
  if (rule == "CL31") return "; Mplus can use labelled MODEL sections without groups for longitudinal invariance; magmaan rejects this because that shortcut is outside project/grammar/mplus.md Not planned; instead, write the longitudinal model explicitly in an unqualified MODEL section.";
  if (rule == "CL32") return "; Mplus uses MODEL PRIORS for Bayesian priors or penalized SEM; magmaan rejects this because priors and penalties are outside project/grammar/mplus.md Not planned; instead, remove MODEL PRIORS for an unpenalized linear SEM, or retain penalized estimation in Mplus.";
  if (rule == "MS01") return "; Mplus requires complete BY/ON/WITH/PON/PWITH, variance, bracket or growth statements; magmaan rejects this because malformed syntax or expansion beyond 100000 rows cannot define a bounded model; instead, write complete explicit relations with semicolon terminators, closed brackets and smaller lists.";
  if (rule == "MS03") return "; Mplus requires latent names distinct from observed names and earlier definitions of second-order indicators; magmaan cannot resolve an invalid factor topology; instead, rename conflicting factors and define first-order factors before second-order BY statements.";
  if (rule == "MS05") return "; Mplus pairs equally sized PON/PWITH lists; magmaan rejects this because unequal lists have no defined pairing; instead, write equally sized left and right lists.";
  if (rule == "MS08") return "; Mplus models explicitly mentioned x moments while conditioning on remaining x variables; magmaan does not reproduce mixed conditioning; instead, complete all x moment mentions in the overall MODEL, or remove all x moment mentions.";
  if (rule == "MS09") return "; Mplus uses BY factor sets and target modifiers for ESEM rotation; magmaan rejects this because ESEM is outside project/grammar/mplus.md Not planned; instead, write one ordinary factor per BY statement with explicit loadings.";
  if (rule == "MS10") return "; Mplus uses class or level sections for mixture/multilevel models; magmaan rejects this because these families are outside project/grammar/mplus.md Not planned; instead, write a single-level ordinary MODEL or explicit GROUPING groups.";
  if (rule == "MS11") return "; Mplus ignores NOMEANSTRUCTURE with default observed information and retains means; magmaan does not reproduce the ignored setting; instead, add INFORMATION = EXPECTED or remove NOMEANSTRUCTURE.";
  if (rule == "LB01") return "; Mplus fixes bare @ at a data-dependent automatic start; magmaan does not emulate Mplus automatic starts; instead, write @value with an explicit numeric fixed value.";
  if (rule == "LB02") return "; Mplus attaches parenthesized labels to parameter items on the same physical line; magmaan rejects this because a label without same-line items has no parameter target; instead, move the label onto the line containing its parameter items.";
  if (rule == "LB03") return "; Mplus 9.1 rejects tokens after a parenthesized label on the same line; magmaan preserves that input-error boundary; instead, move the next item or statement to a new line.";
  if (rule == "LB04") return "; Mplus uses named labels or integer equality numbers with matching lists and bounded suffix ranges; magmaan rejects this because invalid, mixed or unmatched labels cannot define equalities; instead, use letter-led names or integers, close parentheses and match the item count; put individually labelled items on separate lines.";
  if (rule == "LB05") return "; Mplus assigns label groups per left-hand element or a full row-major list; magmaan rejects this because mismatched label counts cannot define the intended parameter ties; instead, give each left-hand group one shared label or one label per right-hand parameter.";
  if (rule == "MG01") return "; Mplus uses GROUPING or labelled FILE entries to define groups; magmaan cannot combine incompatible group sources or exceed 100000 replicated rows; instead, use one explicit GROUPING schema or distinct labelled FILE entries, with fewer groups/relations.";
  if (rule == "MG02") return "; Mplus orders GROUPING groups by numeric code and FILE/summary groups by declaration order; magmaan rejects this because inconsistent counts or empty groups cannot supply the group moments; instead, match NGROUPS and NOBSERVATIONS to the summary blocks and supply observations in every group.";
  if (rule == "MG03") return "; Mplus supports explicit codes and data-dependent GROUPING forms; magmaan imports explicit integer codes only; instead, recode groups to integers in R and write g (1 = g1 2 = g2), including g in NAMES.";
  if (rule == "MG06") return "; Mplus overrides parameters in one declared group and can change some indicator roles; magmaan has a common variable-role contract and cannot preserve group-only topology; instead, write one declared label per MODEL section; put relations in the overall MODEL and fix them in the other groups.";
  if (rule == "IV01") return "; Mplus expands first-order BY invariance shortcuts for multiple groups without partial invariance; magmaan cannot expand structural, second-order or single-group shortcuts; instead, declare groups and an overall first-order BY model, or write ordinary grouped MODEL statements.";
  if (rule == "IV03") return "; Mplus 9.1 rejects categorical METRIC as unidentified; magmaan follows that Mplus input-error boundary; instead, use CONFIGURAL or SCALAR for categorical outcomes.";
  if (rule == "IV04") return "; Mplus runs several invariance models and difference tests for a setting list; magmaan returns one model specification; instead, write exactly one CONFIGURAL, METRIC or SCALAR setting.";
  if (rule == "CT01") return "; Mplus uses two through ten outcome categories and thresholds determined by the data; magmaan needs a matching bounded category schema; instead, supply matching category counts or recode every outcome to two through ten categories.";
  if (rule == "CT02") return "; Mplus uses indexed thresholds instead of categorical intercepts; magmaan rejects this because unindexed or out-of-schema thresholds cannot map to response moments; instead, declare CATEGORICAL and write [u$1] through [u$k] within the observed category count.";
  if (rule == "CT03") return "; Mplus expands forward threshold ranges with one common variable or threshold index; magmaan rejects this because a reversed or doubly changing range has no supported threshold ordering; instead, write both endpoints in ascending order, keeping one variable or one index fixed.";
  if (rule == "CT04") return "; Mplus uses scale factors for DELTA and residual variances for THETA; magmaan rejects this because the other parameter form cannot represent that response parameterization; instead, use DELTA with {u} scales or THETA with categorical residual variances.";
  if (rule == "CT05") return "; Mplus requires THETA when a categorical outcome both influences and is influenced; magmaan follows that response-parameterization restriction; instead, write PARAMETERIZATION = THETA.";
  if (rule == "CT07") return "; Mplus requires categorical variables to be outcomes and every category to occur in every group; magmaan cannot build unmatched group response moments; instead, model each CATEGORICAL variable as an outcome and supply matching category schemas in all groups.";
  if (rule == "CT08") return "; Mplus can fit categorical correlation-summary inputs; magmaan needs individual observations for its categorical moment preparation; instead, supply individual categorical data instead of summary data.";
  if (rule == "GR01") return "; Mplus defines distinct latent growth factors in the overall MODEL; magmaan cannot change the common growth topology in a group override; instead, define distinct growth factors in the overall MODEL and override only group parameters.";
  if (rule == "GR02") return "; Mplus requires enough fixed time scores to identify polynomial growth; magmaan cannot identify the underspecified loading powers; instead, fix at least one time score per growth factor.";
  if (rule == "GR07") return "; Mplus uses random slope/loading, interaction, random variance and varying-time forms after |; magmaan rejects this because those families are outside project/grammar/mplus.md Not planned; instead, write a fixed-time growth series with explicit @ time scores, or retain the original family in Mplus.";
  if (rule == "CN01") return "; Mplus enforces label/NEW equalities and inequalities during estimation; magmaan requires valid equalities and deliberately refuses inequalities because active-bound inference needs boundary asymptotics (project/scope.md); instead, write a valid equality over free labels; drop variance inequalities and use covariance = psd or barrier in fit_model(); parameter orderings remain outside scope.";
  if (rule == "CN02") return "; Mplus declares NEW parameters and derives quantities through acyclic expressions; magmaan cannot resolve duplicate/cyclic names or unbounded derived expansions; instead, declare distinct letter-led NEW names with numeric starts and acyclic bounded definitions.";
  if (rule == "CN03") return "; Mplus expands DO loops with ascending integer limits and up to three indices (#, $, %); magmaan bounds loop expansion to 100000 statements; instead, write DO (first,last) with ascending nonnegative integers and reduce loop limits.";
  if (rule == "CN05") return "; Mplus computes total/specific IND and VIA effects, with MOD/value forms for causal models; magmaan rejects this because causal-effect models are outside project/grammar/mplus.md Not planned and path expansion is bounded; instead, write y IND [mediators] x or y VIA m x over declared variables and reduce oversized path graphs.";
  if (rule == "DA01") return "; Mplus reads numeric ASCII using FREE or Fortran-like fixed FORMAT; magmaan implements bounded Fw.d/w.d, X, Tn, / and repeats; instead, write FREE or a valid bounded fixed FORMAT and supply numeric records of at most 10000 characters.";
  if (rule == "DA02") return "; Mplus reads free-format summary matrices with optional MEANS and NOBSERVATIONS per group; magmaan cannot map inconsistent summary blocks or intercepts without means; instead, supply free-format covariance/correlation blocks with matching counts; add MEANS and a mean vector for intercepts.";
  if (rule == "DA03") return "; Mplus interprets one global missing symbol or numeric flags per NAMES list/ALL after FORMAT scaling; magmaan cannot resolve malformed flags or unknown/reversed variable lists; instead, write MISSING = * or ALL (-9); use BLANK only with fixed FORMAT and list valid variables in schema order.";
  if (rule == "CL19") return "; Mplus uses MODEL settings to alter means, covariances or invariance defaults; magmaan cannot import an empty setting; instead, write NOCOVARIANCES, NOMEANSTRUCTURE with INFORMATION = EXPECTED, or one supported invariance setting.";
  if (rule == "CL25") return "; Mplus selects one INFORMATION convention and uses execution controls for its estimator; magmaan reports those controls without importing fitting conventions; instead, write one INFORMATION = OBSERVED, EXPECTED or COMBINATION setting and choose magmaan fitting controls explicitly.";
  return {};
}
}  // namespace magmaan::parse::detail
