// @generated by dev/vendor-cpp.sh from include/magmaan/robust/weighted_inference.hpp — DO NOT EDIT; re-run `just vendor`.
#pragma once

#include <cstdint>
#include <vector>

#include <Eigen/Core>

#include "magmaan/expected.hpp"
#include "magmaan/estimate/fit.hpp"
#include "magmaan/estimate/gmm/moment_quadratic.hpp"
#include "magmaan/data/raw_data.hpp"
#include "magmaan/robust/robust.hpp"
#include "magmaan/data/sample_stats.hpp"
#include "magmaan/model/matrix_rep.hpp"
#include "magmaan/spec/partable.hpp"

namespace magmaan::estimate {

using data::RawData;
using data::SampleStats;
using robust::MeanVarAdjustedResult;
using robust::SatorraBentlerResult;
using robust::ScaledShiftedResult;

struct WeightedMomentBlock {
  Eigen::MatrixXd jacobian;  // model moments wrt full free theta
  Eigen::MatrixXd weight;    // estimator weight for this moment block
  Eigen::MatrixXd gamma;     // NACOV/meat for this moment block
  std::int64_t n_obs = 0;
};

struct WeightedRobustResult {
  Eigen::MatrixXd vcov;
  Eigen::VectorXd se;
  Eigen::VectorXd eigvals;
  double chisq_standard = 0.0;
  int df = 0;
  robust::SatorraBentlerResult satorra_bentler;
  robust::MeanVarAdjustedResult mean_var_adjusted;
  robust::ScaledShiftedResult scaled_shifted;
};

post_expected<WeightedRobustResult>
robust_weighted_moments(const std::vector<WeightedMomentBlock>& blocks,
                        const Eigen::MatrixXd& K,
                        double fmin);

// Parameter-space sandwich {A1, B1} in the moment metric, the LS counterpart
// of `robust::param_space_sandwich`: per-unit bread A1 = Σ_b (n_b/N)·Δ_bᵀW_bΔ_b
// and meat B1 = Σ_b (n_b/N)·Δ_bᵀW_bΓ̂_bW_bΔ_b, with W the ESTIMATION weight
// (not Γ_NT⁻¹). Always full θ-space (K_con empty): the robust score-test caller
// projects equality constraints itself. No inversion is performed, so a
// singular A1 is fine. The per-direction robust scaling c = gᵀB1g / gᵀA1g is
// NOT invariant to the scale of W (B1 carries W twice); callers must pass the
// same W the score/information evaluation used.
post_expected<robust::ParamSpaceSandwich>
weighted_param_space_sandwich(const std::vector<WeightedMomentBlock>& blocks);

// Moment-metric sandwich for a continuous moment-quadratic (ULS/GLS/WLS/DWLS)
// fit, evaluated at `est.theta` (which may belong to an augmented partable —
// the robust modification-index path calls this at the freed-candidate null
// point). `weight` follows the `robust_continuous_ls` convention (empty ⇒ ULS
// identity). The three overloads differ in the Γ̂ source: per-block supplied,
// empirical from complete-data raw, or model-implied Γ_NT — blockdiag(M_b,
// gamma_nt(M_b)) with M_b = Σ̂_b(θ) (Structured) or S_b (Unstructured). The
// Γ_NT meat with the GLS weight reproduces B1 = A1 (c ≡ 1) exactly.
post_expected<robust::ParamSpaceSandwich>
continuous_ls_param_space_sandwich(spec::LatentStructure pt,
                                   const model::MatrixRep& rep,
                                   const data::SampleStats& samp,
                                   const Estimates& est,
                                   const gmm::Weight& weight,
                                   const std::vector<Eigen::MatrixXd>& gamma);

post_expected<robust::ParamSpaceSandwich>
continuous_ls_param_space_sandwich(spec::LatentStructure pt,
                                   const model::MatrixRep& rep,
                                   const data::SampleStats& samp,
                                   const Estimates& est,
                                   const gmm::Weight& weight,
                                   const data::RawData& raw);

post_expected<robust::ParamSpaceSandwich>
continuous_ls_param_space_sandwich(spec::LatentStructure pt,
                                   const model::MatrixRep& rep,
                                   const data::SampleStats& samp,
                                   const Estimates& est,
                                   const gmm::Weight& weight,
                                   robust::WeightMoments nt_moments);

// Moment-quadratic least-squares objective F(θ) = ½·r̃(θ)ᵀr̃(θ). The `weight`
// is the only thing that distinguishes the estimators: empty ⇒ ULS; a
// normal-theory weight (`gmm::normal_theory_weight`) ⇒ GLS; a caller-supplied
// weight ⇒ WLS / DWLS.
post_expected<double>
evaluate_ls_objective(spec::LatentStructure pt,
                      const model::MatrixRep& rep,
                      const data::SampleStats& samp,
                      const Eigen::VectorXd& theta,
                      const gmm::Weight& weight);

// Continuous-LS reference χ². An empty `weight` ⇒ ULS, reported via Browne's
// residual-based normal-theory statistic; a non-empty `weight` ⇒ GLS / WLS,
// reported as 2N·fmin.
post_expected<double>
continuous_ls_chisq(data::SampleStats samp,
                    spec::LatentStructure pt,
                    const model::MatrixRep& rep,
                    const Estimates& est,
                    const gmm::Weight& weight);

// Non-robust (information-inverse) standard errors for a continuous
// moment-quadratic fit: the npar × npar LS information `Σ_b n_b·Δ_bᵀ W_b Δ_b`,
// with `Δ_b` the model-moment Jacobian and `W_b` the estimator weight (empty
// ⇒ ULS identity). Its inverse — through `inference::vcov`, which folds in any
// equality constraints — is the `se = "standard"` covariance, the non-sandwich
// counterpart to `robust_continuous_ls`.
post_expected<Eigen::MatrixXd>
ls_information(spec::LatentStructure pt,
               const model::MatrixRep& rep,
               const data::SampleStats& samp,
               const Estimates& est,
               const gmm::Weight& weight);

// Robust (sandwich) inference for a continuous moment-quadratic fit. `weight`
// follows the same convention as above (empty ⇒ ULS identity weight). `gamma`
// supplies the per-block moment NACOV directly, or `raw` supplies the raw data
// from which it is estimated.
post_expected<WeightedRobustResult>
robust_continuous_ls(spec::LatentStructure pt,
                     const model::MatrixRep& rep,
                     const data::SampleStats& samp,
                     const Estimates& est,
                     const gmm::Weight& weight,
                     const std::vector<Eigen::MatrixXd>& gamma);

post_expected<WeightedRobustResult>
robust_continuous_ls(spec::LatentStructure pt,
                     const model::MatrixRep& rep,
                     const data::SampleStats& samp,
                     const Estimates& est,
                     const gmm::Weight& weight,
                     const data::RawData& raw);

}  // namespace magmaan::estimate
