test_that("ordinary mixed DWLS inference and reporting use the exact policy", {
  d <- hs()
  ordered <- paste0("x", 1:3)
  for (v in ordered) d[[v]] <- ordered(cut(d[[v]], 3))
  syntax <- "f =~ x1 + a*x2 + b*x3\ng =~ x4 + x5 + x6\ng ~ f"
  model <- magmaan_model(syntax, prototype = d, ordered = ordered)
  null <- magmaan_model(paste(syntax, "a == b", sep = "\n"), prototype = d, ordered = ordered)
  f1 <- magmaan(model, d, estimator = "DWLS")
  f0 <- magmaan(null, d, estimator = "DWLS")
  deferred <- infer(magmaan(model, d, estimator = "DWLS", inference = FALSE))
  expect_equal(deferred$inference, f1$inference)
  expect_equal(vcov(f1), stats::vcov(as_lab_fit(f1), regime = "sandwich_ij"), ignore_attr = TRUE)
  expect_true(all(is.finite(confint(f1))))
  expect_output(print(summary(f1)), "fit.function")
  a <- anova(f0, f1)
  expect_match(attr(a, "unavailable")[["score"]], "unsupported_model")
  expect_true(is.finite(a$pvalue[a$reference %in% "sb" & a$test == "fit_function_difference"]))
  cached <- infer(f1, lavaan_compat = "WLSMV")
  expect_identical(cached$inference, f1$inference)
  expect_equal(vcov(cached), vcov(f1))
  expect_true(all(is.finite(vcov(cached, lavaan_compat = "WLSMV"))))
  unsupported <- infer(f1, lavaan_compat = "ULSMV")
  expect_identical(unsupported$lavaan_compat$ULSMV$status$reason,
                   rep("unsupported_model", 2))
  wlsm <- infer(f1, lavaan_compat = "WLSM")
  expect_identical(wlsm$lavaan_compat$WLSM$status$reason, rep("unsupported_model", 2))
  err <- tryCatch(vcov(f1, lavaan_compat = "ULSMV"),
                  magmaan_inference_unavailable = identity)
  expect_identical(err$reason, "unsupported_model")
})
