// @generated by r-package/tools/vendor-cpp.sh from cpp/include/magmaan/estimate/frontier/convergence_policy.hpp — DO NOT EDIT; re-run `just vendor`.
#pragma once

#include <string>

#include "magmaan/estimate/diagnostics.hpp"

namespace magmaan::estimate::frontier {

struct NewtonDistanceInterval;

enum class ConvergencePolicyKind { Explicit, Compatibility };
enum class RequiredStationarity { FirstOrder, Newton, Both };

// Explicit policies never choose a weaker criterion based on available data.
// Geometry/feasibility tolerances belong to evidence collection. These are
// assessment thresholds and can be changed without reevaluating an objective.
struct ConvergencePolicy {
  ConvergencePolicyKind kind = ConvergencePolicyKind::Explicit;
  RequiredStationarity stationarity = RequiredStationarity::FirstOrder;
  bool require_objective_consistency = false;
  double objective_relative_tol = 1e-6;
  double stationarity_tol = 1e-3;
  NewtonAccuracyOptions newton;
  // Opt-in: the entire construction-aware interval must be within budget.
  // Missing or unresolved bounds stay unchecked; no condition-cap fallback.
  bool require_verified_inputs = false;
};
ConvergencePolicy compatibility_convergence_policy();
ConvergencePolicy first_order_convergence_policy();
ConvergencePolicy newton_convergence_policy();

struct ConvergenceCheck {
  FitCheck status = FitCheck::Unchecked;
  bool required = false;
  std::string reason;
};
struct ConvergenceAssessment {
  FitCheck status = FitCheck::Unchecked;
  StationarityDomain domain = StationarityDomain::Ambient;
  ConvergencePolicy policy;
  ConvergenceCheck objective;
  ConvergenceCheck objective_consistency;
  ConvergenceCheck feasibility;
  ConvergenceCheck first_order;
  ConvergenceCheck newton;
  // Populated only for Compatibility; preserves the historical FitVerdict ABI.
  FitVerdict compatibility_verdict;
};

// Assess already collected summaries. Numeric values are reassessed rather
// than trusting stored pass/fail flags. No optimizer status participates in
// either policy. Use an owning report to retain the Hessian and factorization.
ConvergenceAssessment assess_convergence(
    const FitDiagnostics& evidence, ConvergencePolicy policy = {},
    const NewtonDistanceInterval* interval = nullptr);

} // namespace magmaan::estimate::frontier
