// @generated by dev/vendor-cpp.sh from include/magmaan/estimate/frontier/sphere.hpp — DO NOT EDIT; re-run `just vendor`.
#pragma once

// Sphere-chart estimation (frontier; not a lavaan feature). Design:
// papers/global-gauge-sem/work/notes/2026-09-23-implementation-plan.md
//
// The estimator is unchanged; only the chart the optimizer walks in differs.
// For every gauge unit found by `analyze_gauge`, the loading vector is driven
// as a unit-norm direction a = Q beta / ||beta|| inside the unit's loading
// span (in indicator-standardized units by default), with the latent
// (co)variances free and signed. The radius of beta does not enter the model;
// the gauge pin rho * (||beta||^2 - 1)^2 fixes it without biasing anything,
// because the objective gradient is tangent to the sphere and the pin
// gradient is radial. Every other parameter keeps its ordinary affine
// reduction, and slots that are not gauge units stay in the user's chart.
//
// The fitted point is then translated into the user's chart and finalized
// there with `evaluate_at`, so whenever the user-chart estimate exists the
// returned `Estimates` is the ordinary result (lavaan parity is inherited)
// and all post-fit code applies unchanged. When the user's chart does not
// contain the point (a marker loading of exactly zero, or a non-positive
// variance for a std.lv latent) `user_chart` is false and only the sphere
// report is meaningful.

#include <cstdint>
#include <functional>
#include <limits>
#include <vector>

#include <Eigen/Core>

#include "magmaan/data/raw_data.hpp"
#include "magmaan/data/sample_stats.hpp"
#include "magmaan/estimate/bounds.hpp"
#include "magmaan/estimate/fit.hpp"
#include "magmaan/estimate/frontier/gauge.hpp"
#include "magmaan/estimate/gmm/moment_quadratic.hpp"
#include "magmaan/expected.hpp"
#include "magmaan/model/matrix_rep.hpp"
#include "magmaan/optim/problem.hpp"
#include "magmaan/optim/terminal_audit.hpp"
#include "magmaan/spec/partable.hpp"

namespace magmaan::estimate::frontier {

enum class SphereMetric : std::uint8_t {
  UnitFree,  // sum_j lambda_j^2 / s_jj = 1 (sample indicator variances)
  Raw,       // sum_j lambda_j^2 = 1
};

struct SphereOptions {
  // rho in rho * (||beta||^2 - 1)^2, on the objective's 0.5 F scale. Affects
  // conditioning only.
  double       pin_weight = 1.0;
  SphereMetric metric = SphereMetric::UnitFree;
  // A marker-type unit whose loading direction has |l(a)| below this value is
  // reported as outside the user's chart: the translated estimate would carry
  // loadings of order 1 / pole_tol. 0 disables the tolerance (exact zero only).
  double       pole_tol = 1e-6;
};

struct SphereReport {
  GaugePlan             plan;
  spec::LatentStructure internal_pt;      // gauge-free partable
  Eigen::VectorXd       internal_theta;   // its free parameters at the solution
  Eigen::VectorXd       driven;           // optimizer coordinates at the solution
  double fmin_internal = std::numeric_limits<double>::quiet_NaN();  // pin excluded
  double pin_residual  = std::numeric_limits<double>::quiet_NaN();  // max | ||beta|| - 1 |
  UserChartScales       scales;           // user-chart scales, singular units
  ChartResidual         residual;         // user restrictions after translation
  optim::OptimStatus    optimizer_status = optim::OptimStatus::Converged;
  int                   iterations = 0;
  int                   f_evals = 0;
  int                   g_evals = 0;
  double                grad_inf_norm = -1.0;
  optim::TerminalAudit  driven_audit = {};
};

struct SphereFit {
  bool         user_chart = false;  // true: `estimates` is the user-chart result
  Estimates    estimates;
  SphereReport report;
};

// The ML objective in driven coordinates (pin included), for inspection and
// derivative checks. `internal_theta` maps driven coordinates to the free
// parameters of `internal_pt`.
struct SphereProblem {
  optim::ScalarProblem  problem;
  Eigen::VectorXd       start;
  GaugePlan             plan;
  spec::LatentStructure internal_pt;
  std::function<Eigen::VectorXd(const Eigen::VectorXd&)> internal_theta;
};
fit_expected<SphereProblem>
ml_sphere_problem(spec::LatentStructure pt, const model::MatrixRep& rep,
                  const SampleStats& samp, const Eigen::VectorXd& x0,
                  SphereOptions sphere = {});

// Normal-theory ML. `x0` are start values in the user's chart (size
// pt.n_free()). Box bounds may constrain only weight-0 parameters and give
// sign bounds on scale-dependent ones; a unit whose loadings are bounded
// passes through (see `analyze_gauge`).
fit_expected<SphereFit>
fit_ml_sphere(spec::LatentStructure pt, const model::MatrixRep& rep,
              const SampleStats& samp, const Eigen::VectorXd& x0,
              Bounds bounds = {}, Backend backend = Backend::NloptLbfgs,
              OptimOptions opts = ml_optim_options(),
              SphereOptions sphere = {});

// Fixed-weight moment-quadratic estimation on the continuous moment stack:
// empty `weight` gives ULS, a caller-supplied weight WLS/DWLS.
fit_expected<SphereFit>
fit_gmm_sphere(spec::LatentStructure pt, const model::MatrixRep& rep,
               const SampleStats& samp, const Eigen::VectorXd& x0,
               gmm::Weight weight = {}, Bounds bounds = {},
               Backend backend = Backend::NloptLbfgs, OptimOptions opts = {},
               SphereOptions sphere = {});

// Complete-data ML over the covariance-honest (PSD) domain, composed with the
// sphere chart. The PSD fit is already an equality-constrained SLSQP problem,
// so here the unit norm is imposed as one smooth equality per unit (regular
// everywhere on the sphere) and the loading span and ties as linear
// equalities, all handed to `fit_ml_psd` on the internal partable. The result
// is translated and finalized in the user's chart with the PSD stationarity
// domain.
fit_expected<SphereFit>
fit_ml_psd_sphere(spec::LatentStructure pt, const model::MatrixRep& rep,
                  const SampleStats& samp, const Eigen::VectorXd& x0,
                  Backend backend = Backend::NloptSlsqp,
                  OptimOptions opts = ml_psd_optim_options(),
                  PsdFitOptions psd_opts = ml_psd_options(),
                  SphereOptions sphere = {});

// Full-information ML over raw continuous data (the fit_fiml objective).
fit_expected<SphereFit>
fit_fiml_sphere(spec::LatentStructure pt, const model::MatrixRep& rep,
                const data::RawData& raw, const Eigen::VectorXd& x0,
                Backend backend = Backend::NloptLbfgsSlsqpFallback,
                OptimOptions opts = {}, SphereOptions sphere = {});

// Normal-theory GLS (sample-based fixed weight).
fit_expected<SphereFit>
fit_gls_sphere(spec::LatentStructure pt, const model::MatrixRep& rep,
               const SampleStats& samp, const Eigen::VectorXd& x0,
               Bounds bounds = {}, Backend backend = Backend::NloptLbfgs,
               OptimOptions opts = {}, SphereOptions sphere = {});

}  // namespace magmaan::estimate::frontier
