// @generated by dev/vendor-cpp.sh from src/estimate/gmm/gp.cpp — DO NOT EDIT; re-run `just vendor`.
#include "magmaan/estimate/gmm/gp.hpp"

#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <algorithm>
#include <Eigen/Cholesky>
#include <Eigen/Core>
#include <Eigen/QR>

#include "magmaan/error.hpp"
#include "magmaan/expected.hpp"
#include "magmaan/estimate/constraints.hpp"
#include "magmaan/model/matrix_rep.hpp"
#include "magmaan/model/model_evaluator.hpp"
#include "magmaan/optim/problem.hpp"
#include "magmaan/spec/partable.hpp"

namespace magmaan::estimate::gmm {

namespace {

using estimate::build_eq_constraints;
using estimate::EqConstraints;

FitError fit_err(FitError::Kind kind, std::string detail) {
  return FitError{kind, std::move(detail), 0, 0.0};
}

// Golub–Pereyra splits the free parameters into two blocks: the *nonlinear*
// loadings/structural coefficients (Λ, Β) that drive the outer optimization,
// and the *conditionally-linear* (co)variances/intercepts (Θ, Ψ, ν, α) that an
// inner linear least-squares solves for at each outer step.
enum class BlockKind : std::uint8_t { None, Nonlinear, Linear };

BlockKind block_kind_for(model::MatId mat) noexcept {
  switch (mat) {
    case model::MatId::Lambda:
    case model::MatId::Beta:
      return BlockKind::Nonlinear;
    case model::MatId::Theta:
    case model::MatId::Psi:
    case model::MatId::Nu:
    case model::MatId::Alpha:
      return BlockKind::Linear;
  }
  return BlockKind::None;
}

std::string_view block_kind_name(BlockKind k) noexcept {
  switch (k) {
    case BlockKind::None: return "none";
    case BlockKind::Nonlinear: return "nonlinear";
    case BlockKind::Linear: return "linear";
  }
  return "?";
}

// The β/α split: which equality-constraint basis columns carry the nonlinear
// parameters, which carry the linear ones, plus the affine reparameterization
// pieces (θ₀, K_β, K_α) restricted to each block.
struct Classification {
  EqConstraints constraints;
  std::vector<Eigen::Index> beta_cols;
  std::vector<Eigen::Index> alpha_cols;
  Eigen::VectorXd beta0;
  Eigen::MatrixXd K_beta;
  Eigen::MatrixXd K_alpha;
};

// Classify the free parameters into the nonlinear (β) and linear (α) blocks.
// Fails (NumericIssue) when the model is not separable: an unsupported matrix
// location, an equality constraint that mixes the two kinds, or no linear
// parameter to profile.
fit_expected<Classification>
classify(const spec::LatentStructure& pt, const model::ModelEvaluator& ev,
         const Eigen::VectorXd& theta_start,
         const std::vector<GpBlockKind>* override_kinds = nullptr) {
  auto con_or = build_eq_constraints(pt);
  if (!con_or.has_value()) {
    return std::unexpected(fit_err(
        FitError::Kind::NumericIssue,
        "SNLLS compatibility: constraint: " + con_or.error().detail));
  }
  EqConstraints con = std::move(*con_or);
  const auto locs = ev.param_locations();
  if (static_cast<std::int32_t>(locs.size()) != pt.n_free()) {
    return std::unexpected(fit_err(
        FitError::Kind::NumericIssue,
        "SNLLS compatibility: parameter-location count does not match n_free"));
  }
  if (override_kinds != nullptr &&
      static_cast<std::int32_t>(override_kinds->size()) != pt.n_free()) {
    return std::unexpected(fit_err(
        FitError::Kind::NumericIssue,
        "SNLLS compatibility: block-kind override count does not match n_free"));
  }

  Classification out;
  out.constraints = std::move(con);
  std::vector<BlockKind> full_kind(locs.size(), BlockKind::None);
  for (std::size_t k = 0; k < locs.size(); ++k) {
    if (override_kinds != nullptr) {
      full_kind[k] = (*override_kinds)[k] == GpBlockKind::Linear
                         ? BlockKind::Linear
                         : BlockKind::Nonlinear;
    } else {
      full_kind[k] = block_kind_for(locs[k].mat);
    }
    if (full_kind[k] == BlockKind::None) {
      return std::unexpected(fit_err(
          FitError::Kind::NumericIssue,
          "SNLLS compatibility: free parameter " + std::to_string(k + 1) +
              " has unsupported matrix location"));
    }
  }

  constexpr double tol = 1e-10;
  for (Eigen::Index c = 0; c < out.constraints.Kmat.cols(); ++c) {
    BlockKind kind = BlockKind::None;
    for (Eigen::Index r = 0; r < out.constraints.Kmat.rows(); ++r) {
      if (std::abs(out.constraints.Kmat(r, c)) <= tol) continue;
      const BlockKind rk = full_kind[static_cast<std::size_t>(r)];
      if (kind == BlockKind::None) {
        kind = rk;
      } else if (kind != rk) {
        return std::unexpected(fit_err(
            FitError::Kind::NumericIssue,
            "SNLLS compatibility: equality/linear constraint basis column " +
                std::to_string(c + 1) + " mixes " +
                std::string(block_kind_name(kind)) + " and " +
                std::string(block_kind_name(rk)) + " parameters"));
      }
    }
    if (kind == BlockKind::None) continue;
    if (kind == BlockKind::Nonlinear) out.beta_cols.push_back(c);
    if (kind == BlockKind::Linear) out.alpha_cols.push_back(c);
  }

  if (out.alpha_cols.empty()) {
    return std::unexpected(fit_err(
        FitError::Kind::NumericIssue,
        "SNLLS compatibility: no conditionally linear free parameters to profile"));
  }

  const Eigen::VectorXd q0 = out.constraints.contract(theta_start);
  out.beta0.resize(static_cast<Eigen::Index>(out.beta_cols.size()));
  for (std::size_t i = 0; i < out.beta_cols.size(); ++i) {
    out.beta0(static_cast<Eigen::Index>(i)) = q0(out.beta_cols[i]);
  }

  out.K_beta.resize(out.constraints.npar,
                    static_cast<Eigen::Index>(out.beta_cols.size()));
  for (std::size_t j = 0; j < out.beta_cols.size(); ++j) {
    out.K_beta.col(static_cast<Eigen::Index>(j)) =
        out.constraints.Kmat.col(out.beta_cols[j]);
  }
  out.K_alpha.resize(out.constraints.npar,
                     static_cast<Eigen::Index>(out.alpha_cols.size()));
  for (std::size_t j = 0; j < out.alpha_cols.size(); ++j) {
    out.K_alpha.col(static_cast<Eigen::Index>(j)) =
        out.constraints.Kmat.col(out.alpha_cols[j]);
  }
  return out;
}

// One profiled point: full θ, the profiled residual, and the two Jacobian
// pieces needed downstream (H = J_r·K_α for the inner solve, J_r·K_β for the
// outer Jacobian).
struct ProfilePoint {
  Eigen::VectorXd theta;
  Eigen::VectorXd residual;
  Eigen::MatrixXd H;
  Eigen::MatrixXd jacobian;
  // Telemetry: which path the α-solve took. False on the n_alpha == 0
  // closed-form short-circuit (no solve happens) — readers must gate on
  // whether an α-block existed before attributing this to a fast/fallback
  // choice. See `docs/design/snlls-fast-alpha-solve.md`.
  bool used_fast_solve = false;
};

// Gate on `rcond(HᵀH)` for the fast Cholesky-on-normal-equations α-solve
// in `profile_at`. Higham (Accuracy and Stability of Numerical Algorithms,
// 2nd ed., Thm 20.4) bounds the Cholesky-NE residual relative error at
// `O(u · κ(HᵀH))`; the loss vs the rank-revealing QR is ≤ 1 digit when
// `rcond(HᵀH) > √u ≈ 1.49e-8` in double. The 1e-7 gate adds ~6× headroom
// for Hager's optimistic-bias rcond estimator and any extra amplification
// from the residual product. See `docs/design/snlls-fast-alpha-solve.md`.
constexpr double kFastSolveThreshold = 1e-7;

// Hager 1-norm reciprocal-condition-number estimator
// (Higham §15.2 / LAPACK ?POCON), specialized for a symmetric-PD matrix
// whose Cholesky factor is already in hand. Returns 1 / (‖A‖₁·‖A⁻¹‖₁),
// which is an *upper* bound on the true rcond (Hager's iterate is a
// lower bound on ‖A⁻¹‖₁). Returns 0.0 on any numeric pathology — that
// forces the caller to fall back to the rank-revealing path.
//
// Cost: at most 6 triangular back-solves through the supplied factor,
// O(p²) total — negligible against the O(n·p²) already spent forming
// `A = HᵀH`.
double rcond_pocon_sym(const Eigen::LLT<Eigen::MatrixXd>& llt,
                       const Eigen::MatrixXd& A) {
  const Eigen::Index p = A.rows();
  if (p == 0) return 0.0;
  const double norm_A = A.cwiseAbs().colwise().sum().maxCoeff();
  if (norm_A == 0.0) return 0.0;

  Eigen::VectorXd x = Eigen::VectorXd::Constant(p, 1.0 / static_cast<double>(p));
  double gamma = 0.0;
  for (int k = 0; k < 5; ++k) {
    Eigen::VectorXd y = llt.solve(x);
    if (!y.allFinite()) return 0.0;
    gamma = y.lpNorm<1>();
    Eigen::VectorXd xi(p);
    for (Eigen::Index i = 0; i < p; ++i) {
      xi(i) = (y(i) >= 0.0) ? 1.0 : -1.0;
    }
    Eigen::VectorXd z = llt.solve(xi);  // A symmetric ⇒ A⁻ᵀ = A⁻¹
    if (!z.allFinite()) return 0.0;
    Eigen::Index j;
    const double zmax = z.cwiseAbs().maxCoeff(&j);
    if (k > 0 && zmax <= z.dot(x)) break;
    x.setZero();
    x(j) = 1.0;
  }

  // Higham eq. 15.5 polishing step: alternating signed ramp.
  if (p > 1) {
    Eigen::VectorXd b(p);
    const double scale = static_cast<double>(p - 1);
    for (Eigen::Index i = 0; i < p; ++i) {
      const double s = (i % 2 == 0) ? 1.0 : -1.0;
      b(i) = s * (1.0 + static_cast<double>(i) / scale);
    }
    const Eigen::VectorXd y2 = llt.solve(b);
    if (y2.allFinite()) {
      const double gamma2 = 2.0 * y2.lpNorm<1>() / (3.0 * static_cast<double>(p));
      gamma = std::max(gamma, gamma2);
    }
  }

  if (gamma == 0.0 || !std::isfinite(gamma)) return 0.0;
  return 1.0 / (norm_A * gamma);
}

// Solve the inner linear least-squares for α̂ at a given β.
fit_expected<ProfilePoint>
profile_at(const optim::GmmProblem& base, const Classification& cls,
           const Eigen::VectorXd& beta) {
  Eigen::VectorXd theta_base = cls.constraints.theta0;
  if (cls.K_beta.cols() > 0) theta_base.noalias() += cls.K_beta * beta;

  Eigen::VectorXd r0;
  Eigen::MatrixXd Jr0;
  if (base.eval) {
    auto e0 = base.eval(theta_base);
    if (!e0.has_value()) return std::unexpected(e0.error());
    r0 = std::move(e0->residual);
    Jr0 = std::move(e0->jacobian);
  } else {
    auto r0_or = base.r(theta_base);
    if (!r0_or.has_value()) return std::unexpected(r0_or.error());
    auto Jr0_or = base.J(theta_base);
    if (!Jr0_or.has_value()) return std::unexpected(Jr0_or.error());
    r0 = std::move(*r0_or);
    Jr0 = std::move(*Jr0_or);
  }

  ProfilePoint out;
  // H = ∂r/∂α is invariant in the conditionally-linear α (the residual is
  // affine in Θ/Ψ/ν/α), so evaluating it at θ_base is exact — and so is the
  // inner linear least-squares it drives.
  out.H = Jr0 * cls.K_alpha;

  const Eigen::Index n_alpha = cls.K_alpha.cols();
  if (n_alpha == 0) {
    out.residual = std::move(r0);
    out.theta    = theta_base;
    out.jacobian = Jr0 * cls.K_beta;
    return out;
  }

  // Two-path α-solve. Try Cholesky-on-normal-equations first; fall back
  // to rank-revealing QR if the Gram is not numerically PD or if the
  // estimated rcond drops below `kFastSolveThreshold`. Whichever path
  // wins is reused for the β-gauge back-solve below so both consumers
  // see the same inverse.
  const Eigen::MatrixXd HtH = out.H.transpose() * out.H;
  Eigen::LLT<Eigen::MatrixXd> llt(HtH);
  Eigen::ColPivHouseholderQR<Eigen::MatrixXd> H_qr;
  bool used_fast = false;
  if (llt.info() == Eigen::Success &&
      rcond_pocon_sym(llt, HtH) > kFastSolveThreshold) {
    used_fast = true;
  }
  if (!used_fast) {
    H_qr.compute(out.H);
  }

  const Eigen::VectorXd alpha_hat = used_fast
      ? Eigen::VectorXd(llt.solve(out.H.transpose() * (-r0)))
      : Eigen::VectorXd(H_qr.solve(-r0));
  out.residual = r0 + out.H * alpha_hat;
  out.theta    = theta_base + cls.K_alpha * alpha_hat;
  out.used_fast_solve = used_fast;

  // The outer (β) Jacobian must be taken at the *profiled* point θ̂(β):
  // ∂r/∂Λ depends on the latent (co)variances Ψ that α̂ has just set, so
  // J_β at θ_base would be wrong.
  auto Jr = base.J(out.theta);
  if (!Jr.has_value()) return std::unexpected(Jr.error());
  out.jacobian = *Jr * cls.K_beta;
  if (out.jacobian.cols() > 0) {
    const Eigen::MatrixXd coeff = used_fast
        ? Eigen::MatrixXd(llt.solve(out.H.transpose() * out.jacobian))
        : Eigen::MatrixXd(H_qr.solve(out.jacobian));
    out.jacobian.noalias() -= out.H * coeff;
  }
  return out;
}

}  // namespace

bool gp_compatible(const spec::LatentStructure& pt,
                   const model::ModelEvaluator& ev,
                   const Eigen::VectorXd& theta0) {
  return classify(pt, ev, theta0).has_value();
}

fit_expected<GpProblem>
gp_impl(const optim::GmmProblem& base, const spec::LatentStructure& pt,
        const model::ModelEvaluator& ev, const Eigen::VectorXd& theta0,
        const std::vector<GpBlockKind>* override_kinds) {
  auto cls_or = classify(pt, ev, theta0, override_kinds);
  if (!cls_or.has_value()) return std::unexpected(cls_or.error());
  auto cls = std::make_shared<Classification>(std::move(*cls_or));

  // The optimizer queries residual and Jacobian at the same β; cache the
  // profile so the inner solve runs once per distinct β.
  struct Cache {
    bool            valid = false;
    Eigen::VectorXd beta;
    ProfilePoint    point;
  };
  auto cache = std::make_shared<Cache>();
  // Shared with the closure below and surfaced through `GpProblem` so
  // callers can read the final tallies after the outer optimizer
  // returns. Each successful `profile_at()` cache miss with a non-empty
  // α-block bumps exactly one of these.
  auto n_alpha_solve_fast     = std::make_shared<std::int32_t>(0);
  auto n_alpha_solve_fallback = std::make_shared<std::int32_t>(0);
  const bool has_alpha = cls->K_alpha.cols() > 0;
  auto profiled = [base, cls, cache, n_alpha_solve_fast,
                   n_alpha_solve_fallback, has_alpha](
                      const Eigen::VectorXd& beta)
      -> fit_expected<std::reference_wrapper<const ProfilePoint>> {
    if (cache->valid && cache->beta.size() == beta.size() &&
        (cache->beta.array() == beta.array()).all()) {
      return std::cref(cache->point);
    }
    auto p = profile_at(base, *cls, beta);
    if (!p.has_value()) return std::unexpected(p.error());
    if (has_alpha) {
      if (p->used_fast_solve) ++(*n_alpha_solve_fast);
      else                    ++(*n_alpha_solve_fallback);
    }
    cache->valid = true;
    cache->beta  = beta;
    cache->point = std::move(*p);
    return std::cref(cache->point);
  };

  optim::GmmProblem out;
  out.n_resid = base.n_resid;
  out.n_param = cls->K_beta.cols();
  out.r = [profiled](const Eigen::VectorXd& beta)
      -> fit_expected<Eigen::VectorXd> {
    auto p = profiled(beta);
    if (!p.has_value()) return std::unexpected(p.error());
    return p->get().residual;
  };
  out.J = [profiled](const Eigen::VectorXd& beta)
      -> fit_expected<Eigen::MatrixXd> {
    auto p = profiled(beta);
    if (!p.has_value()) return std::unexpected(p.error());
    return p->get().jacobian;
  };
  out.eval = [profiled](const Eigen::VectorXd& beta)
      -> fit_expected<optim::LsEvaluation> {
    auto p = profiled(beta);
    if (!p.has_value()) return std::unexpected(p.error());
    return optim::LsEvaluation{p->get().residual, p->get().jacobian};
  };
  out.expand = [profiled, cls](const Eigen::VectorXd& beta) -> Eigen::VectorXd {
    auto p = profiled(beta);
    if (p.has_value()) return p->get().theta;
    Eigen::VectorXd theta = cls->constraints.theta0;
    if (cls->K_beta.cols() > 0) theta.noalias() += cls->K_beta * beta;
    return theta;
  };
  return GpProblem{
      std::move(out), cls->beta0,
      static_cast<std::int32_t>(cls->beta_cols.size()),
      static_cast<std::int32_t>(cls->alpha_cols.size()),
      std::move(n_alpha_solve_fast),
      std::move(n_alpha_solve_fallback)};
}

fit_expected<GpProblem>
gp(const optim::GmmProblem& base, const spec::LatentStructure& pt,
   const model::ModelEvaluator& ev, const Eigen::VectorXd& theta0) {
  return gp_impl(base, pt, ev, theta0, nullptr);
}

fit_expected<GpProblem>
gp(const optim::GmmProblem& base, const spec::LatentStructure& pt,
   const model::ModelEvaluator& ev, const Eigen::VectorXd& theta0,
   const std::vector<GpBlockKind>& block_kinds) {
  return gp_impl(base, pt, ev, theta0, &block_kinds);
}

}  // namespace magmaan::estimate::gmm
