// @generated by r-package/tools/vendor-cpp.sh from cpp/src/parse/mplus_parser.cpp — DO NOT EDIT; re-run `just vendor`.
#include "magmaan/parse/mplus_parser.hpp"
#include "detail_mplus_diagnostic.hpp"
#include <algorithm>
#include <charconv>
#include <map>
#include <set>
#include <optional>
#include <tuple>
#include <cmath>
#include "magmaan/parse/parser.hpp"
#include "magmaan/parse/expr_format.hpp"

namespace magmaan::parse {
namespace {
// production: name ::= letter (letter | digit | '_')*; case folding [LX04]
std::string lower(std::string_view value) {
  std::string result(value);
  for (auto& c : result) if (c >= 'A' && c <= 'Z') c += 'a' - 'A';
  return result;
}
struct Token { std::string text; SourceSpan span; };
struct Item { std::string name; std::optional<double> fixed, start; SourceSpan span; bool explicit_free = false; };
struct Row { std::string lhs, rhs, label; Op op; std::optional<double> fixed, start; SourceSpan span; };
class Lowerer {
 public:
  MplusModel out;
  bool group_mode = false;
  std::vector<std::int32_t> category_counts;
  std::vector<std::vector<Row>> grouped_rows;
  std::vector<Token> tokens;
  std::vector<std::string> observed, latent;
  std::set<std::string> observed_set, latent_set;
  std::map<std::string, std::string> spelling;
  std::vector<std::vector<std::string>> label_groups;
  std::vector<Row> rows;
  std::map<std::tuple<std::string,Op,std::string>,std::size_t> row_indices;
  std::optional<ParseError> error;
  std::set<std::string> dependent, predictors, indicators, defined, factor_has_loading;
  std::set<std::string> growth_outcomes, growth_factors;
  std::string constraint_syntax;
  SourceSpan overall_body;
  // production: model_body ::= model_statement*
  explicit Lowerer(MplusInput input) {
    out.input = std::move(input); out.notes = out.input.notes; overall_body=out.input.model_body;
    for (const auto& name : out.input.analysis) { observed.push_back(lower(name)); observed_set.insert(lower(name)); spelling[lower(name)] = name; }
  }
  // production: model_statement ::= relation | variance_statement | mean_statement | scale_statement | bar_statement | section_marker; classified rejection
  void reject(SourceSpan span, std::string rule, std::string detail) {
    if (!error) error = ParseError{ParseError::Kind::RejectedConstruct, span,
      std::to_string(span.line) + ":" + std::to_string(span.col) + " [" + rule + "] found '" + out.input.source.substr(span.begin,std::min<std::size_t>(span.end-span.begin,120)) + "': " + detail + detail::mplus_rejection_contract(rule)};
  }
  // production: categorical_value ::= variable_range+
  bool is_categorical(const std::string& name) const {
    return std::any_of(out.input.categorical.begin(),out.input.categorical.end(),[&](const auto& n) {return lower(n)==name;});
  }
  // production: name ::= letter (letter | digit | '_')*; latent role resolution [NM04]
  bool is_latent(const std::string& name) const { return latent_set.contains(name); }
  // production: token ::= name | number | punct
  void lex() {
    const auto& source = out.input.source;
    std::uint32_t line = 1, col = 1;
    for (std::size_t i = 0; i < out.input.model_body.begin; ++i) {
      if (source[i] == '\n') { ++line; col = 1; } else ++col;
    }
    bool block = false, comment = false;
    for (std::size_t i = out.input.model_body.begin; i < out.input.model_body.end;) {
      const char c = source[i];
      if (c == '\n') { ++line; col = 1; comment = false; ++i; continue; }
      if (block) { if (c == '*' && i + 1 < source.size() && source[i+1] == '!') { block = false; i += 2; col += 2; } else { ++i; ++col; } continue; }
      if (comment) { ++i; ++col; continue; }
      if (c == '!') { block = i + 1 < source.size() && source[i+1] == '*'; comment = !block; ++i; ++col; continue; }
      if (i < out.input.model_body.begin || i >= out.input.model_body.end || c == ' ' || c == '\t' || c == '\r' || c == ',') { ++i; ++col; continue; }
      const auto begin = i; const auto column = col;
      if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '.') {
        do { ++i; ++col; } while (i < source.size() && ((source[i] >= 'a' && source[i] <= 'z') || (source[i] >= 'A' && source[i] <= 'Z') || (source[i] >= '0' && source[i] <= '9') || source[i] == '_' || source[i] == '.'));
      } else { ++i; ++col; }
      tokens.push_back({lower(std::string_view(source).substr(begin,i-begin)), {static_cast<std::uint32_t>(begin),static_cast<std::uint32_t>(i),line,column}});
    }
  }
  std::vector<std::string> expand(const Token& first, const Token* last) {
    const auto locate = [](const auto& list, const auto& name) { return std::find(list.begin(),list.end(),name); };
    const auto& list = is_latent(first.text) ? latent : observed;
    const auto a = locate(list,first.text);
    if (a == list.end()) {
      bool excluded = false;
      for (const auto& n : out.input.names) if (lower(n) == first.text) excluded = true;
      reject(first.span,"NM03","unknown MODEL name '" + first.text + "'" + (excluded ? " is in NAMES but not USEVARIABLES" : " is neither an analysis variable nor a defined factor") + "; Mplus resolves analysis variables and factors; add it to USEVARIABLES or define it with BY first"); return {};
    }
    if (!last) return {first.text};
    if (is_latent(first.text) != is_latent(last->text) && (latent_set.contains(last->text) || observed_set.contains(last->text))) { reject(first.span,"NM04","mixed latent/observed range '"+first.text+"-"+last->text+"'; Mplus keeps these two orders separate; list the names individually instead"); return {}; }
    const auto b = locate(list,last->text);
    if (b == list.end() || b < a) { reject(first.span,is_latent(first.text) ? "NM04" : "NM03","invalid range '" + first.text + "-" + last->text + "'; Mplus uses analysis order for observed names and BY order for latent names, without mixing them; list names in forward order instead"); return {}; }
    return {a,b+1};
  }
  // production: signed_number ::= '-'? number
  std::optional<double> number(const std::vector<Token>& ts, std::size_t& i) {
    const auto original = i;
    double sign = 1;
    if (i < ts.size() && ts[i].text == "-") { sign = -1; ++i; }
    if (i == ts.size()) { i = original; return {}; }
    double result = 0; const auto& text = ts[i].text;
    const auto parsed = std::from_chars(text.data(),text.data()+text.size(),result);
    if (text.empty() || !std::all_of(text.begin(),text.end(),[](char c) { return (c >= '0' && c <= '9') || c == '.'; }) || std::count(text.begin(),text.end(),'.') > 1) { i = original; return {}; }
    if (parsed.ec != std::errc{} || parsed.ptr != text.data()+text.size() || !std::isfinite(result)) { i = original; return {}; }
    ++i; return sign * result;
  }
  // production: rhs_item ::= variable_range modifier?
  std::vector<Item> items(const std::vector<Token>& ts, std::size_t begin, std::size_t end) {
    std::vector<Item> result;
    for (auto i = begin; i < end && !error;) {
      auto first = ts[i++]; const Token* last = nullptr;
      if (i < end && ts[i].text == "-") { ++i; if (i == end) { reject(first.span,"NM03","unfinished range; Mplus needs two endpoints; list names instead"); break; } last = &ts[i++]; }
      auto names = expand(first,last); std::optional<double> fixed, start; bool explicit_free = false;
      if (i < end && (ts[i].text == "@" || ts[i].text == "*")) {
        const bool fix = ts[i++].text == "@"; explicit_free = !fix;
        auto value = number(ts,i);
        if (fix && !value) reject(first.span,"LB01","bare '@' fixes at a data-dependent Mplus start; magmaan does not emulate those starts; write @value instead");
        if (fix) fixed = value; else start = value;
      }
      auto at = first.span; at.end = ts[i-1].span.end;
      for (auto& n : names) result.push_back({n,fixed,start,at,explicit_free});
    }
    return result;
  }
  // production: threshold_item ::= threshold_range modifier?
  std::vector<Item> threshold_items(const std::vector<Token>& ts, std::size_t begin, std::size_t end) {
    std::vector<Item> result;
    for (auto i=begin;i<end && !error;) {
      const auto first=ts[i++];
      if (i==end || ts[i].text!="$") {
        auto last=i;
        while(last<end && ts[last].text!="$" && ts[last].text!="(") ++last;
        // Ordinary means share the existing item/range parser.
        if(last<end && ts[last].text=="$") last=last>i ? last-1 : i;
        if(last==i) last=i;
        auto ordinary=items(ts,i-1,last);
        result.insert(result.end(),ordinary.begin(),ordinary.end()); i=last; continue;
      }
      auto index=[&](std::size_t& at)->int {
        if(at==end || ts[at++].text!="$" || at==end) {reject(first.span,"CT02","missing threshold index; write $1 or a higher positive integer instead");return 0;}
        int n=0; const auto& value=ts[at++].text;
        auto parsed=std::from_chars(value.data(),value.data()+value.size(),n);
        if(parsed.ec!=std::errc{} || parsed.ptr!=value.data()+value.size() || n<1 || n>9) {reject(first.span,"CT01","threshold index must be 1 through 9; Mplus permits at most ten categories; supply a valid index instead");return 0;}
        return n;
      };
      const int a=index(i); int b=a; Token last=first;
      if(i<end && ts[i].text=="-") {++i;if(i==end) {reject(first.span,"CT03","unfinished threshold range; supply both endpoints instead");break;} last=ts[i++];b=index(i);}
      if(!is_categorical(first.text) || !is_categorical(last.text)) {reject(first.span,"CT02","threshold on a non-categorical variable; declare CATEGORICAL instead");break;}
      std::vector<std::string> names;
      if(first.text==last.text) names={first.text};
      else if(a==b) names=expand(first,&last);
      else {reject(first.span,"CT03","threshold range changes both variable and index; use one variable or one index per range instead");break;}
      if(b<a) {reject(first.span,"CT03","backward threshold range; list thresholds from lowest to highest instead");break;}
      std::optional<double> fixed,start;bool explicit_free=false;
      if(i<end && (ts[i].text=="@" || ts[i].text=="*")) {const bool fix=ts[i++].text=="@";auto value=number(ts,i);if(fix && !value) reject(first.span,"LB01","bare threshold @ requires a data-dependent start; write @value instead");if(fix) fixed=value;else {start=value;explicit_free=true;}}
      auto span=first.span;span.end=ts[i-1].span.end;
      for(const auto& name:names) for(int n=a;n<=b;++n) result.push_back({name+"$"+std::to_string(n),fixed,start,span,explicit_free});
    }
    return result;
  }
  // production: line_label ::= '(' label_group+ ')'
  std::vector<std::string> labels(const std::vector<Token>& ts, std::size_t begin, std::size_t end) {
    std::vector<std::string> result;
    label_groups.clear();
    bool numeric = false, named = false;
    for (auto i = begin; i < end && !error;) {
      const auto first = ts[i++];
      const auto group_begin = result.size();
      auto add = [&](std::string label) {
        if (label.empty() || !std::all_of(label.begin(), label.end(), [](char c) { return (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_'; })) { reject(first.span,"LB04","invalid label '" + label + "'; Mplus accepts names or integer equality sets; write a name starting with a letter or an integer instead"); return; }
        const bool num = !label.empty() && label.front() >= '0' && label.front() <= '9';
        if ((num && !std::all_of(label.begin(),label.end(),[](char c) {return c >= '0' && c <= '9';})) || (!num && !(label.front() >= 'a' && label.front() <= 'z'))) { reject(first.span,"LB04","label '"+label+"' is not an integer equality number or a name beginning with a letter; Mplus accepts those two forms; write an integer or a letter-led label instead"); return; }
        if (num) { const auto nonzero = label.find_first_not_of('0'); label = nonzero == std::string::npos ? "0" : label.substr(nonzero); }
        numeric |= num; named |= !num;
        result.push_back(num ? ".eq" + label + "." : label);
      };
      if (i < end && ts[i].text == "-") {
        ++i; if (i == end) { reject(first.span,"LB04","unfinished label range; Mplus requires endpoints; list labels instead"); break; }
        auto last = ts[i++];
        auto a = first.text.size(), b = last.text.size();
        while (a && first.text[a-1] >= '0' && first.text[a-1] <= '9') --a;
        while (b && last.text[b-1] >= '0' && last.text[b-1] <= '9') --b;
        unsigned x = 0,y = 0;
        auto pa = std::from_chars(first.text.data()+a,first.text.data()+first.text.size(),x);
        auto pb = std::from_chars(last.text.data()+b,last.text.data()+last.text.size(),y);
        if (pa.ec != std::errc{} || pb.ec != std::errc{} || first.text.substr(0,a) != last.text.substr(0,b) || y < x || y-x > 100000) { reject(first.span,"LB04","invalid label range; Mplus expands numeric suffixes; list matching labels instead"); break; }
        for (auto n = x;; ++n) { add(first.text.substr(0,a)+std::to_string(n)); if (n == y) break; }
      } else add(first.text);
      label_groups.emplace_back(result.begin()+static_cast<std::ptrdiff_t>(group_begin),result.end());
    }
    if (numeric && named) reject(ts[begin].span,"LB04","mixed numeric equality sets and named labels; Mplus uses a single kind in each list; use only numbers or only names");
    return result;
  }
  void put(Row row, bool replace = true) {
    if (row.op == Op::Covariance && row.rhs < row.lhs) std::swap(row.lhs,row.rhs);
    const auto key = std::tuple{row.lhs,row.op,row.rhs};
    const auto found = row_indices.find(key);
    if (found == row_indices.end()) {
      if (rows.size() >= 100000) { reject(row.span,"MS01","model expands beyond 100000 parameters; Mplus expands lists, but magmaan bounds expansion; reduce the model or list a smaller set of relations instead"); return; }
      row_indices.emplace(key,rows.size()); rows.push_back(std::move(row));
    } else if (replace) rows[found->second] = std::move(row);
  }
  // production: constraint_body ::= (new_statement | equality_statement | do_statement | plot_statement)*
  std::vector<std::vector<Token>> constraint_statements() {
    std::vector<std::vector<Token>> result;
    const auto original = out.input.model_body;
    for (const auto body : out.input.constraint_bodies) {
      out.input.model_body = body; tokens.clear(); lex();
      std::vector<Token> current;
      for (const auto& token : tokens) {
        if (token.text == ";") { if (!current.empty()) result.push_back(current); current.clear(); }
        else current.push_back(token);
      }
      if (!current.empty()) reject(current.front().span,"CN01","unterminated constraint; Mplus requires ';'; add a terminator");
    }
    out.input.model_body = original;
    return result;
  }
  // production: do_statement ::= 'DO' '(' integer ',' integer ')' constraint_body
  void expand_do(std::vector<Token> ts, std::size_t depth,
                 std::vector<std::vector<Token>>& expanded) {
    if (ts.empty() || error) return;
    if (expanded.size() >= 100000) {reject(ts.front().span,"CN03","DO expansion exceeds 100000 statements; reduce the loop limits"); return;}
    if (ts.front().text != "do") {expanded.push_back(std::move(ts)); return;}
    if (depth >= 3 || ts.size() < 6 || ts[1].text != "(" || ts[4].text != ")") {
      reject(ts.front().span,"CN03","malformed DO loop; Mplus uses DO (first,last) and at most three nested indices (#, $, %); write that form"); return;
    }
    int a=0,b=0;
    auto pa=std::from_chars(ts[2].text.data(),ts[2].text.data()+ts[2].text.size(),a);
    auto pb=std::from_chars(ts[3].text.data(),ts[3].text.data()+ts[3].text.size(),b);
    if(pa.ec!=std::errc{} || pa.ptr!=ts[2].text.data()+ts[2].text.size() || pb.ec!=std::errc{} || pb.ptr!=ts[3].text.data()+ts[3].text.size() || a<0 || b<a || b-a>10000) {
      reject(ts.front().span,"CN03","invalid DO limits; use ascending nonnegative integer limits within the bounded expansion");return;
    }
    const std::string marker=depth==0 ? "#" : depth==1 ? "$" : "%";
    for(int n=a;n<=b && !error;++n) {
      std::vector<Token> body;
      for(std::size_t i=5;i<ts.size();++i) {
        if(ts[i].text==marker) {
          if(!body.empty() && body.back().span.end==ts[i].span.begin) {body.back().text+=std::to_string(n);body.back().span.end=ts[i].span.end;}
          else body.push_back({std::to_string(n),ts[i].span});
        } else body.push_back(ts[i]);
      }
      expand_do(std::move(body),depth+1,expanded);
    }
  }
  // production: mplus_expr ::= expr
  std::string expression(const std::vector<Token>& ts, std::size_t first, std::size_t last) {
    std::string value;
    for(auto i=first;i<last;++i) {
      auto text=ts[i].text;
      if(text=="*" && i+1<last && ts[i+1].text=="*") {text="^";++i;}
      if(text=="phi" && i+1<last && ts[i+1].text=="(") text="pnorm";
      value+=text+" ";
    }
    return value;
  }
  // production: new_statement ::= 'NEW' '(' (name_range ('*' signed_number)?)+ ')' ';'
  void constraints() {
    std::vector<std::vector<Token>> statements;
    for(auto ts:constraint_statements()) expand_do(std::move(ts),0,statements);
    std::map<std::string,double> newly_declared;
    for(const auto& ts:statements) if(ts.front().text=="new") {
      if(ts.size()<4 || ts[1].text!="(" || ts.back().text!=")") {reject(ts.front().span,"CN02","malformed NEW declaration; write NEW (name*start ...)");return;}
      for(std::size_t i=2;i+1<ts.size();) {
        auto name=ts[i++];std::vector<std::string> names_to_add{name.text};
        if(i+1<ts.size() && ts[i].text=="-") {
          ++i;auto last=ts[i++];auto n=name.text.size(),m=last.text.size();
          while(n && name.text[n-1]>='0' && name.text[n-1]<='9') --n;
          while(m && last.text[m-1]>='0' && last.text[m-1]<='9') --m;
          int a=0,b=0;auto pa=std::from_chars(name.text.data()+n,name.text.data()+name.text.size(),a);auto pb=std::from_chars(last.text.data()+m,last.text.data()+last.text.size(),b);
          if(pa.ec!=std::errc{} || pb.ec!=std::errc{} || name.text.substr(0,n)!=last.text.substr(0,m) || b<a || b-a>10000) {reject(name.span,"CN02","invalid NEW range; list names or use matching numeric suffixes");return;}
          names_to_add.clear();for(int j=a;j<=b;++j) names_to_add.push_back(name.text.substr(0,n)+std::to_string(j));
        }
        double start=.5;
        if(i+1<ts.size() && ts[i].text=="*") {++i;auto v=number(ts,i);if(!v) {reject(name.span,"CN02","NEW start must be numeric; supply a number after '*'");return;}start=*v;}
        for(const auto& n:names_to_add) {
          if(n.empty() || n.front()<'a' || n.front()>'z' || !std::all_of(n.begin(),n.end(),[](char c){return (c>='a' && c<='z') || (c>='0' && c<='9') || c=='_';}) || observed_set.contains(n) || latent_set.contains(n) || newly_declared.contains(n) || std::any_of(rows.begin(),rows.end(),[&](const auto& row){return row.label==n;})) {
            reject(name.span,"CN02","NEW name conflicts with an existing name or is invalid; declare a distinct parameter name");return;
          }
          newly_declared[n]=start;
        }
      }
    }
    std::set<std::string> loop_names, plot_names;
    for(const auto& ts:statements) {
      if(ts.size()>2 && ts[0].text=="loop") loop_names.insert(ts[2].text);
      if(ts[0].text=="plot") for(std::size_t i=2;i+1<ts.size();++i) plot_names.insert(ts[i].text);
    }
    const auto plot_expression=[&](const auto& ts) {
      return std::any_of(ts.begin(),ts.end(),[&](const auto& token){return loop_names.contains(token.text);}) ||
        (plot_names.contains(ts[0].text) && !newly_declared.contains(ts[0].text));
    };
    std::set<std::string> derived;
    for(const auto& ts:statements) if(ts.size()>2 && ts[1].text=="=" && newly_declared.contains(ts[0].text)) derived.insert(ts[0].text);
    std::map<std::string,std::vector<Token>> definitions;
    for(const auto& ts:statements) if(ts.size()>2 && ts[1].text=="=" && derived.contains(ts[0].text) && !plot_expression(ts)) {
      definitions.try_emplace(ts[0].text,ts.begin()+2,ts.end());
    }
    std::set<std::string> expanding;
    const auto expand_definition=[&](auto&& self,const std::vector<Token>& input)->std::vector<Token> {
      std::vector<Token> result;
      for(const auto& token:input) {
        auto hit=definitions.find(token.text);
        if(hit==definitions.end()) result.push_back(token);
        else {
          if(expanding.contains(token.text)) {reject(token.span,"CN02","cyclic NEW definition; use acyclic derived parameters");return {};}
          expanding.insert(token.text);auto body=self(self,hit->second);expanding.erase(token.text);
          result.push_back({"(",token.span});result.insert(result.end(),body.begin(),body.end());result.push_back({")",token.span});
        }
        if(result.size()>100000) {reject(token.span,"CN02","derived expression expansion exceeds 100000 tokens; simplify the definitions");return {};}
      }
      return result;
    };
    std::set<std::string> emitted_definitions;
    for(const auto& ts:statements) {
      if(ts.front().text=="new") continue;
      if(ts.front().text=="loop" || ts.front().text=="plot") {out.notes.push_back({MplusClass::Reported,ts.front().span,"CN03","LOOP/PLOT plotting request is not imported"});continue;}
      if(plot_expression(ts)) {out.notes.push_back({MplusClass::Reported,ts.front().span,"CN03","LOOP/PLOT expression is a plotting function, not an estimable parameter"});continue;}
      auto eq=std::find_if(ts.begin(),ts.end(),[](const auto& t){return t.text=="=" || t.text=="<" || t.text==">";});
      if(eq==ts.end()) {reject(ts.front().span,"CN01","constraint needs '='; write an explicit or implicit equality");return;}
      if(eq->text!="=") {reject(eq->span,"CN01","Mplus enforces inequalities during estimation; magmaan deliberately refuses them because active-bound inference needs boundary asymptotics (project/scope.md). For variance positivity drop the inequality and use covariance = 'psd' or 'barrier' in fit_model(); parameter orderings are not supported");return;}
      auto i=static_cast<std::size_t>(eq-ts.begin());
      if(i==1 && derived.contains(ts[0].text) && emitted_definitions.insert(ts[0].text).second) constraint_syntax+=expression(ts,0,i)+":= "+expression(ts,i+1,ts.size())+"\n";
      else {
        auto lhs=expand_definition(expand_definition,{ts.begin(),eq});
        auto rhs=expand_definition(expand_definition,{eq+1,ts.end()});if(error) return;
        constraint_syntax+=expression(lhs,0,lhs.size())+"== "+expression(rhs,0,rhs.size())+"\n";
      }
    }
    for(const auto& [name,start]:newly_declared) if(!derived.contains(name)) {
      rows.push_back({name,"",name,Op::AuxiliaryParam,{},start,out.input.model_body});
      if(!grouped_rows.empty()) for(std::size_t g=0;g<grouped_rows.size();++g)
        grouped_rows[g].push_back({name,"",g==0 ? name : "",Op::AuxiliaryParam,g==0 ? std::nullopt : std::optional<double>{0},start,out.input.model_body});
    }
  }
  // production: indirect_statement ::= name ('IND' name+ | 'VIA' name name) ';'
  void indirect(std::vector<Row>& model_rows, const std::vector<Token>& ts, std::size_t group) {
    if(ts.size()<3 || (ts[1].text!="ind" && ts[1].text!="via") || (ts[1].text=="via" && ts.size()!=4) ||
       std::any_of(ts.begin(),ts.end(),[](const auto& t){return t.text=="(" || t.text==")" || t.text=="mod";})) {
      reject(ts.front().span,"CN05","causal-effect value/MOD form or malformed indirect request; causal-effect models are outside scope; use y IND [mediators] x or y VIA m x");return;
    }
    for(std::size_t i=0;i<ts.size();++i) if(i!=1 && !observed_set.contains(ts[i].text) && !latent_set.contains(ts[i].text)) {reject(ts[i].span,"CN05","unknown indirect path name; use analysis variables or defined factors");return;}
    std::map<std::string,std::vector<std::pair<std::string,std::string>>> edges;
    for(std::size_t i=0;i<model_rows.size();++i) {
      auto& row=model_rows[i];if(row.op!=Op::Regression) continue;
      std::string coefficient;
      if(row.fixed) coefficient=std::to_string(*row.fixed);
      else {if(row.label.empty()) row.label="mi_g"+std::to_string(group)+"_"+row.lhs+"_"+row.rhs;coefficient=row.label;}
      edges[row.rhs].push_back({row.lhs,coefficient});
    }
    const auto& target=ts.front().text;const auto& origin=ts.back().text;
    std::vector<std::string> terms;
    if(ts[1].text=="ind" && ts.size()>3) {
      std::string product="1",from=origin;
      for(auto i=ts.size()-1;i>1;--i) {
        const auto to=i==2 ? target : ts[i-1].text;
        auto edge=std::find_if(edges[from].begin(),edges[from].end(),[&](const auto& item){return item.first==to;});
        if(edge==edges[from].end()) {product="0";break;}product+="*"+edge->second;from=to;
      }
      terms.push_back(product);
    } else {
      std::set<std::string> visited{origin};
      const auto walk=[&](auto&& self,const std::string& from,std::string product,std::size_t length,bool via)->void {
        if(error) return;
        for(const auto& [to,coefficient]:edges[from]) {
          if(visited.contains(to)) continue;
          const auto term=product.empty() ? coefficient : product+"*"+coefficient;
          const bool through=via || (ts[1].text=="via" && to==ts[2].text);
          if(to==target) {if(length>=1 && (ts[1].text=="ind" || through)) terms.push_back(term);}
          else {visited.insert(to);self(self,to,term,length+1,through);visited.erase(to);}
          if(terms.size()>100000) {reject(ts.front().span,"CN05","indirect path expansion exceeds 100000 paths; reduce the graph");return;}
        }
      };
      walk(walk,origin,"",0,false);
    }
    std::string name="ind_g"+std::to_string(group)+"_"+target;
    for(std::size_t i=1;i<ts.size();++i) name+="_"+ts[i].text;
    std::string sum;for(const auto& term:terms) {if(!sum.empty()) sum+=" + ";sum+=term;}
    constraint_syntax+=name+" := "+(sum.empty() ? "0" : sum)+"\n";
  }
  // production: indirect_statement ::= name ('IND' name+ | 'VIA' name name) ';'
  void indirects() {
    const auto original=out.input.model_body;
    for(const auto body:out.input.indirect_bodies) {
      out.input.model_body=body;tokens.clear();lex();std::vector<Token> current;
      for(const auto& token:tokens) {
        if(token.text==";") {
          if(!current.empty()) {
            if(grouped_rows.empty()) indirect(rows,current,1);
            else for(std::size_t g=0;g<grouped_rows.size();++g) indirect(grouped_rows[g],current,g+1);
          }
          current.clear();
        } else current.push_back(token);
        if(error) break;
      }
      if(!current.empty() && !error) reject(current.front().span,"CN05","unterminated indirect request; add ';'");
    }
    out.input.model_body=original;
  }
  // production: mplus_expr ::= expr; shared expression lowering
  bool append_expressions() {
    if(constraint_syntax.empty()) return true;
    auto parsed=Parser::parse(constraint_syntax);
    if(!parsed) {reject(out.input.model_body,"CN01","invalid expression: "+parsed.error().detail);return false;}
    out.flat.expression_text=std::move(parsed->source_text);
    out.flat.constraints=std::move(parsed->constraints);
    return true;
  }
  // production: bar_statement ::= name name? name? name? '|' rhs_item+ ';'
  void put_growth(Row row) {
    row.span=overall_body;
    auto found=row_indices.find(std::tuple{row.lhs,row.op,row.rhs});
    const bool replace=group_mode && found!=row_indices.end() && rows[found->second].span.begin==overall_body.begin;
    put(std::move(row),replace);
  }
  // production: bar_statement ::= name name? name? name? '|' rhs_item+ ';'
  void growth(const std::vector<Token>& ts) {
    const auto bar=std::find_if(ts.begin(),ts.end(),[](const auto& t){return t.text=="|";});
    if(bar==ts.end()) return;
    const auto n=static_cast<std::size_t>(bar-ts.begin());
    if(n<1 || n>4 || std::any_of(ts.begin(),ts.end(),[](const auto& t){return t.text=="on" || t.text=="pon" || t.text=="by" || t.text=="xwith" || t.text=="at";})) {
      reject(bar->span,"GR07","random slope/loading, interaction or individually varying time form; these Mplus model families are outside project/scope.md; write fixed-time polynomial growth instead");return;
    }
    auto outcomes=items(ts,n+1,ts.size());if(error) return;
    if(outcomes.empty() || (outcomes.size()==1 && !outcomes.front().fixed)) {
      reject(bar->span,"GR07","bare single outcome after '|'; Mplus interprets a random variance; write a growth series with explicit time scores instead");return;
    }
    const auto fixed_count=std::count_if(outcomes.begin(),outcomes.end(),[](const auto& item){return item.fixed.has_value();});
    if(n>2 && fixed_count<static_cast<std::ptrdiff_t>(n)) {
      reject(bar->span,"GR02","insufficient fixed time scores for polynomial growth; Mplus requires enough fixed scores; fix at least one score per growth factor instead");return;
    }
    for(std::size_t k=0;k<n;++k) {
      const auto& factor=ts[k].text;
      if(!is_latent(factor)) {reject(ts[k].span,"GR01","growth factor was not declared in the overall MODEL; put the common growth topology in MODEL and override group parameters explicitly");return;}
      growth_factors.insert(factor);defined.insert(factor);factor_has_loading.insert(factor);
      const bool categorical=is_categorical(outcomes.front().name) || is_latent(outcomes.front().name);
      put_growth({factor,"","",Op::Intercept,k==0 && categorical && (!group_mode || grouped_rows.empty()) ? std::optional<double>{0} : std::nullopt,{},out.input.model_body});
      for(std::size_t j=0;j<outcomes.size();++j) {
        const auto& outcome=outcomes[j];
        growth_outcomes.insert(outcome.name);indicators.insert(outcome.name);dependent.insert(outcome.name);
        std::optional<double> loading=k==0 ? std::optional<double>{1} : outcome.fixed ? std::optional<double>{std::pow(*outcome.fixed,static_cast<int>(k))} : std::nullopt;
        std::string label;
        if(!loading) {
          label="gr_"+factor+"_"+outcome.name;
          if(k>1) constraint_syntax+=label+" == gr_"+ts[1].text+"_"+outcome.name+"^"+std::to_string(k)+"\n";
        }
        put_growth({factor,outcome.name,label,Op::Measurement,loading,outcome.start,out.input.model_body});
        if(!is_categorical(outcome.name)) put_growth({outcome.name,"","",Op::Intercept,0,{},out.input.model_body});
        else {
          const bool theta=out.input.parameterization=="THETA";
          put_growth({outcome.name,outcome.name,"",theta ? Op::Covariance : Op::ResponseScale,j==0 && (!group_mode || grouped_rows.empty()) ? std::optional<double>{1} : std::nullopt,{},out.input.model_body});
        }
      }
    }
  }
  // production: model_statement ::= relation | variance_statement | mean_statement | scale_statement | bar_statement | section_marker
  void statement(const std::vector<Token>& ts) {
    if (ts.empty()) return;
    // production: mean_statement ::= mean_group+ ';'; scale_statement ::= scale_group+ ';'
    // Each bracket group is a complete segment; never discard later labels.
    if ((ts.front().text == "[" || ts.front().text == "{") &&
        std::count_if(ts.begin(),ts.end(),[&](const auto& t){return t.text == ts.front().text;}) > 1) {
      const auto open = ts.front().text;
      const auto close = open == "[" ? "]" : "}";
      for (std::size_t cursor = 0; cursor < ts.size() && !error;) {
        if (ts[cursor].text != open) { reject(ts[cursor].span,"MS01","unexpected token after bracket group; write a complete bracket group instead"); return; }
        auto end = cursor+1;
        while (end < ts.size() && ts[end].text != close) ++end;
        if (end == ts.size()) { reject(ts[cursor].span,"MS01","unclosed bracket group; close the group instead"); return; }
        ++end;
        if (end < ts.size() && ts[end].text != "(" && ts[end].span.line == ts[end-1].span.line) {
          reject(ts[end].span,"MS01","another bracket group on the same line; Mplus 9.1 rejects it; move each group to a new line instead"); return;
        }
        if (end < ts.size() && ts[end].text == "(") {
          const auto label = end;
          while (end < ts.size() && ts[end].text != ")") ++end;
          if (end == ts.size()) { reject(ts[label].span,"LB04","unclosed label; close its parentheses instead"); return; }
          ++end;
          if (end < ts.size() && ts[end].span.line == ts[end-1].span.line) {
            reject(ts[end].span,"LB03","token after a label on the same line; Mplus 9.1 rejects it; move the next group to a new line instead"); return;
          }
        }
        statement(std::vector<Token>(ts.begin()+static_cast<std::ptrdiff_t>(cursor),ts.begin()+static_cast<std::ptrdiff_t>(end)));
        cursor = end;
      }
      return;
    }
    if (!out.input.data_plan.matrix_type.empty() && !out.input.data_plan.means &&
        std::any_of(ts.begin(),ts.end(),[](const auto& t){return t.text=="[" || t.text=="$";})) {
      reject(ts.front().span,"DA02","an explicit intercept, mean or threshold with summary data without MEANS; Mplus requires MEANS for these parameters (P-DA3); add MEANS and supply a mean vector instead");return;
    }
    for (const auto& t : ts) {
      if ((t.text == "{" || t.text == "$") && out.input.categorical.empty()) { reject(t.span,t.text == "{" ? "CT04" : "CT02","categorical scale or threshold without CATEGORICAL; declare categorical outcomes instead"); return; }
      if (t.text == "|") return; // Growth defaults were expanded before explicit mentions.
      if (t.text == "#" || t.text == "%") { reject(t.span,"MS10","found '"+t.text+"'; Mplus selects mixture or multilevel sections; these families are outside scope; supply a single-group model instead"); return; }
      if (t.text == "~" || (t.text == "*" && &t != &ts.front() && (&t-1)->text == "(")) { reject(t.span,"MS09","found ESEM modifier; Mplus defines rotation targets or factor sets; ESEM is outside scope; specify ordinary BY loadings instead"); return; }
    }
    std::size_t relation = ts.size(); std::string op;
    for (std::size_t i = 0; i < ts.size(); ++i) if (ts[i].text == "by" || ts[i].text == "on" || ts[i].text == "pon" || ts[i].text == "with" || ts[i].text == "pwith") { relation = i; op = ts[i].text; break; }
    const bool scale = ts.front().text == "{";
    const bool mean = ts.front().text == "[" || scale;
    auto begin = mean ? std::size_t{1} : relation < ts.size() ? relation+1 : 0;
    auto end = ts.size();
    if (mean) { auto close = std::find_if(ts.begin(),ts.end(),[](const auto& t) { return t.text == "]" || t.text == "}"; }); if (close == ts.end()) { reject(ts.front().span,"MS01","unclosed mean list; Mplus requires ']'; close the bracket before ';'"); return; } end = static_cast<std::size_t>(close-ts.begin()); }
    if (mean && end+1 < ts.size() && ts[end+1].text != "(") { reject(ts[end+1].span,"MS01","token '"+ts[end+1].text+"' after mean bracket; Mplus accepts a label or semicolon here; finish this statement and write a separate statement instead"); return; }
    if (mean && end+1 < ts.size() && ts[end+1].text == "(") {
      auto label_end = end+2;
      while (label_end < ts.size() && ts[label_end].text != ")") ++label_end;
      if (label_end+1 < ts.size() && ts[label_end+1].span.line != ts[label_end].span.line) {
        reject(ts[label_end+1].span,"MS01","unexpected token after mean or scale label; Mplus requires another bracket group; write a complete bracket group instead"); return;
      }
    }
    auto lhs = relation < ts.size() ? items(ts,0,relation) : std::vector<Item>{};
    if (error) return;
    for (const auto& item : lhs) if (item.fixed || item.start || item.explicit_free) { reject(item.span,"MS01","modifier on left-hand name '"+item.name+"'; Mplus attaches modifiers to right-hand items; write the modifier after the right-hand variable instead"); return; }
    if (relation < ts.size() && (lhs.empty() || begin == end)) { reject(ts[relation].span,"MS01","empty side of '"+op+"'; Mplus requires names on both sides; supply left- and right-hand variables instead"); return; }
    if (mean && begin == end) { reject(ts.front().span,"MS01","empty mean bracket; Mplus requires variable names; write [name] instead"); return; }
    const bool paired = op == "pon" || op == "pwith";
    std::size_t rhs_offset = 0;
    if (paired) {
      std::vector<Token> unlabelled;
      bool in_label = false;
      for (auto i = begin; i < end; ++i) {
        if (ts[i].text == "(") { in_label = true; continue; }
        if (ts[i].text == ")") { in_label = false; continue; }
        if (!in_label) unlabelled.push_back(ts[i]);
      }
      const auto total = items(unlabelled,0,unlabelled.size()).size();
      if (lhs.size() != total) { reject(ts[relation].span,"MS05","unequal lists for '"+op+"'; Mplus pairs corresponding elements; write equally sized lists instead"); return; }
    }
    // Labels attach only to the physical line's items, including row-major LHS expansion.
    for (auto cursor = begin; cursor < (mean ? ts.size() : end) && !error;) {
      if (mean && cursor == end) { ++cursor; continue; }
      auto line_end = cursor;
      while (line_end < end && ts[line_end].span.line == ts[cursor].span.line && ts[line_end].text != "(") ++line_end;
      auto rhs = mean && !scale ? threshold_items(ts,cursor,line_end) : items(ts,cursor,line_end);
      std::size_t label_begin = line_end, label_end = line_end;
      if (mean && line_end == end && end+1 < ts.size() && ts[end+1].text == "(") label_begin = end+1;
      std::vector<std::string> lab;
      if (label_begin < ts.size() && ts[label_begin].text == "(") {
        label_end = label_begin+1;
        while (label_end < ts.size() && ts[label_end].text != ")") ++label_end;
        if (label_end == ts.size()) { reject(ts[label_begin].span,"LB04","unclosed label; Mplus requires ')'; close the label list"); return; }
        if (label_end == label_begin+1) { reject(ts[label_begin].span,"LB04","empty label parentheses; Mplus requires a label or equality number; write a name or integer instead"); return; }
        lab = labels(ts,label_begin+1,label_end);
        if (label_end+1 < ts.size() && ts[label_end+1].span.line == ts[label_end].span.line) { reject(ts[label_end+1].span,"LB03","token '"+ts[label_end+1].text+"' after a label on the same line; Mplus 9.1 rejects it; move the next item to a new line"); return; }
      }
      std::vector<Row> segment;
      if (relation == ts.size()) {
        for (const auto& r : rhs) {
          const auto dollar=r.name.find('$');
          const auto name=r.name.substr(0,dollar);
          if (scale && (!is_categorical(name) || out.input.parameterization=="THETA")) {
            reject(r.span,"CT04","scale-factor statement requires a categorical DELTA outcome; use PARAMETERIZATION = DELTA or a THETA residual variance instead"); return;
          }
          if (mean && !scale && dollar==std::string::npos && is_categorical(name)) {
            reject(r.span,"CT02","bare categorical intercept; Mplus requires a threshold index; write ["+name+"$1] instead"); return;
          }
          if (!mean && is_categorical(name) && out.input.parameterization=="DELTA" && !r.fixed) {
            reject(r.span,"CT04","free categorical residual variance under DELTA; Mplus requires THETA; use PARAMETERIZATION = THETA instead"); return;
          }
          segment.push_back({name,dollar!=std::string::npos ? "t"+r.name.substr(dollar+1) : mean && !scale ? "" : name,"",
              dollar!=std::string::npos ? Op::Threshold : scale ? Op::ResponseScale : mean ? Op::Intercept : Op::Covariance,
              r.fixed,r.start,r.span});
        }
      } else {
        const bool pair = paired;
        if (lhs.size() && rhs.size() > 100000 / lhs.size()) { reject(ts[relation].span,"MS01","relation list expands beyond 100000 parameters; Mplus crosses lists, but magmaan bounds expansion; reduce the lists instead"); return; }
        std::set<std::pair<std::string,std::string>> seen;
        for (std::size_t a = 0; a < lhs.size(); ++a) for (std::size_t b = 0; b < rhs.size(); ++b) {
          if (pair && a != rhs_offset + b) continue;
          const auto& l = lhs[a]; const auto& r = rhs[b];
          auto kind = op == "by" ? Op::Measurement : op == "with" || op == "pwith" ? Op::Covariance : Op::Regression;
          if (kind == Op::Covariance) { auto key = std::minmax(l.name,r.name); if (l.name == r.name || !seen.emplace(key.first,key.second).second) continue; }
          if (kind == Op::Measurement && is_latent(r.name) && !defined.contains(r.name)) { reject(r.span,"MS03","factor '"+r.name+"' appears on BY's right before its definition; Mplus requires earlier BY definition; move that definition first"); return; }
          auto fixed = r.fixed;
          if (kind == Op::Measurement) {
            const bool previous = factor_has_loading.contains(l.name);
            const bool mentioned = row_indices.contains(std::tuple{l.name,kind,r.name});
            if (!group_mode && !previous && b == 0 && !fixed && !r.explicit_free) fixed = 1;
            if (mentioned && !r.fixed) fixed.reset();
            factor_has_loading.insert(l.name); indicators.insert(r.name); dependent.insert(r.name);
          } else if (kind == Op::Regression) { dependent.insert(l.name); predictors.insert(r.name); }
          segment.push_back({l.name,r.name,"",kind,fixed,r.start,r.span});
        }
      }
      if (!lab.empty() && segment.empty()) { reject(ts[label_begin].span,"LB02","label has no parameter items on its line; Mplus labels items on the same physical line; move the label onto the item line instead"); return; }
      const bool grouped = lhs.size() > 1 && label_groups.size() == lhs.size() && !lab.empty();
      if (grouped) {
        for (std::size_t a = 0; a < lhs.size(); ++a) {
          const auto count = static_cast<std::size_t>(std::count_if(segment.begin(),segment.end(),[&](const Row& row) {return row.lhs == lhs[a].name;}));
          if (!count || (label_groups[a].size() != 1 && label_groups[a].size() != count)) { reject(ts[label_begin].span,"LB05","label group for '"+lhs[a].name+"' does not match its right-hand parameters; Mplus assigns one group per left-hand element or a full row-major list; give that group one shared label or one label per parameter instead"); return; }
        }
      }
      if (!grouped && !lab.empty() && lab.size() != 1 && lab.size() != segment.size() && !(lhs.size() > 1 && lab.size() == lhs.size())) { reject(ts[label_begin].span, lhs.size() > 1 ? "LB05" : "LB04","label count does not match parameters; Mplus assigns one shared label, one per left-hand element, or a full row-major list; supply matching labels instead"); return; }
      if (lab.size() > 1 && lhs.size() <= 1) {
        std::set<std::uint32_t> item_spans;
        for (const auto& item : rhs) item_spans.insert(item.span.begin);
        if (item_spans.size() > 1) { reject(ts[label_begin].span,"LB04","label list follows individually listed items; Mplus accepts a matching label list after one range; use a range or place each labelled item on its own line instead"); return; }
      }
      std::vector<std::size_t> group_offsets(lhs.size(),0);
      for (std::size_t i = 0; i < segment.size(); ++i) {
        auto& row = segment[i];
        if (!lab.empty()) {
          std::string assigned;
          if (grouped) {
            const auto a = static_cast<std::size_t>(std::find_if(lhs.begin(),lhs.end(),[&](const Item& item) {return item.name == row.lhs;})-lhs.begin());
            const auto& group = label_groups[a];
            assigned = group[group.size() == 1 ? 0 : group_offsets[a]];
            ++group_offsets[a];
          } else assigned = lab[lab.size() == 1 ? 0 : i];
          if (row.fixed) out.notes.push_back({MplusClass::Reported,row.span,"LB06","label '"+assigned+"' dropped from fixed parameter, as in Mplus"});
          else row.label = std::move(assigned);
        }
        put(std::move(row));
      }
      rhs_offset += rhs.size();
      cursor = label_end > label_begin ? label_end+1 : line_end;
      if (mean && cursor >= end) break;
    }
    if (op == "by") for (const auto& l : lhs) defined.insert(l.name);
  }
  // production: model_qualifier ::= group_label
  void expand_groups() {
    if (!rows.empty() && out.input.groups.size()>100000/rows.size()) {
      reject(out.input.model_body,"MG01","group replication exceeds 100000 parameter rows; Mplus fits larger group models, but magmaan bounds expansion; reduce the number of groups or relations instead");return;
    }
    const auto common = rows;
    const auto key = [](const Row& r) {return std::tuple{r.lhs,r.op,r.rhs};};
    const auto original_dependent=dependent, original_predictors=predictors, original_indicators=indicators;
    const bool shortcut=!out.input.invariance.empty();
    if (shortcut) {
      if (!out.input.group_sections.empty()) { reject(out.input.model_body,"IV01","Mplus shortcuts do not permit partial invariance; magmaan expands an overall first-order BY model only; remove group sections or write ordinary MODEL statements instead"); return; }
      for (const auto& row:common) if (row.span.begin!=out.input.model_body.begin && (row.op!=Op::Measurement || is_latent(row.rhs)) && !(row.op==Op::Covariance && row.lhs==row.rhs && is_latent(row.lhs) && row.fixed==1)) {
        reject(row.span,"IV01","Mplus invariance shortcuts require only first-order BY statements; magmaan does not expand structural or second-order shortcuts; write ordinary grouped MODEL statements instead"); return;
      }
    }
    std::size_t equality=0;
    std::map<std::tuple<std::string,Op,std::string>,std::string> defaults;
    for (const auto& row:common) if (row.label.empty() && !row.fixed &&
        ((row.op==Op::Measurement && !is_latent(row.rhs) && !growth_factors.contains(row.lhs)) || ((row.op==Op::Intercept || row.op==Op::Threshold) && indicators.contains(row.lhs))))
      defaults[key(row)]=".mg"+std::to_string(++equality)+".";
    for (std::size_t g=0; g<out.input.groups.size(); ++g) {
      rows=common; row_indices.clear();
      for (std::size_t i=0;i<rows.size();++i) {
        auto& row=rows[i]; row_indices[key(row)]=i;
        if (defaults.contains(key(row))) row.label=defaults.at(key(row));
        const bool generated=row.span.begin==out.input.model_body.begin;
        if (row.op==Op::Intercept && is_latent(row.lhs) && generated && g>0) row.fixed.reset();
        if (generated && g>0 && indicators.contains(row.lhs) && is_categorical(row.lhs) &&
            ((row.op==Op::ResponseScale && out.input.parameterization=="DELTA") ||
             (row.op==Op::Covariance && row.lhs==row.rhs && out.input.parameterization=="THETA")) &&
            out.input.invariance!="CONFIGURAL") row.fixed.reset();
        if (shortcut) {
          const auto& setting=out.input.invariance;
          if ((setting=="CONFIGURAL" && row.op==Op::Measurement) || (setting!="SCALAR" && (row.op==Op::Intercept || row.op==Op::Threshold) && indicators.contains(row.lhs))) {if (row.label.starts_with(".mg")) row.label.clear();}
          if (row.op==Op::Intercept && is_latent(row.lhs)) row.fixed=(setting=="SCALAR" && g>0) ? std::nullopt : std::optional<double>{0};
          // A fixed factor variance in the overall MODEL identifies the variance
          // version; metric/scalar release it in later groups (TECH1, IV05).
          if (row.op==Op::Covariance && row.lhs==row.rhs && is_latent(row.lhs) && row.fixed==1 && setting!="CONFIGURAL" && g>0) row.fixed.reset();
        }
      }
      group_mode=true;
      for (const auto& section:out.input.group_sections) if (lower(section.label)==lower(out.input.groups[g].label)) {
        const auto body=out.input.model_body; out.input.model_body=section.body;
        tokens.clear(); lex(); std::vector<Token> current;
        // Expand growth in a group before its explicit overrides, as overall.
        for(std::size_t begin=0;begin<tokens.size();) {
          auto end=begin;while(end<tokens.size() && tokens[end].text!=";") ++end;
          growth(std::vector<Token>(tokens.begin()+static_cast<std::ptrdiff_t>(begin),tokens.begin()+static_cast<std::ptrdiff_t>(end)));
          if(error) break;begin=end+1;
        }
        for (const auto& token:tokens) {if (token.text==";") {statement(current);current.clear();} else current.push_back(token); if(error) break;}
        if (!current.empty()) reject(current.front().span,"MS01","group MODEL statement lacks a terminator; Mplus requires ';'; add ';' instead");
        out.input.model_body=body;
        if (error) return;
      }
      if (dependent!=original_dependent || predictors!=original_predictors || indicators!=original_indicators) {
        reject(out.input.model_body,"MG06","a group section changes a variable's indicator, predictor or dependent role; Mplus accepts extra indicators but rejects overall-absent group regressions as ignored statements (P-MG13); magmaan's common variable-role contract cannot preserve such differences; put the relation in the overall MODEL and fix its coefficient in the other groups instead"); return;
      }
      for (const auto& row:rows) if (!out.input.joint_x && (row.op==Op::Covariance || row.op==Op::Intercept) &&
          ((observed_set.contains(row.lhs) && predictors.contains(row.lhs) && !dependent.contains(row.lhs)) ||
           (observed_set.contains(row.rhs) && predictors.contains(row.rhs) && !dependent.contains(row.rhs)))) {
        std::string completion;
        for (const auto& name : out.input.observed_x) completion += (completion.empty() ? "" : " ") + name;
        reject(row.span,"MS08","a group section changes overall x conditioning; complete the joint form in overall MODEL with `"+completion+";`, or remove its variance, mean or WITH mention instead");return;
      }
      grouped_rows.push_back(rows);
    }
    group_mode=false;
    // Union topology: generated zero entries add neither parameters nor df.
    rows=common; row_indices.clear();
    for (std::size_t i=0;i<rows.size();++i) row_indices[key(rows[i])]=i;
    for (const auto& group:grouped_rows) for (const auto& row:group) if (!row_indices.contains(key(row))) {row_indices[key(row)]=rows.size();rows.push_back(row);}
    for (auto& group:grouped_rows) {
      std::map<std::tuple<std::string,Op,std::string>,Row> by_key;
      for (const auto& row:group) by_key.emplace(key(row),row);
      group.clear();
      for (const auto& row:rows) {
        auto found=by_key.find(key(row));
        if (found!=by_key.end()) group.push_back(found->second);
        else {auto zero=row;zero.fixed=0;zero.start.reset();zero.label.clear();zero.span={};group.push_back(std::move(zero));}
      }
    }
  }

  // production: model_body ::= model_statement*
  parse_expected<MplusModel> run() {
    if (out.input.model_body.begin == out.input.model_body.end) {
      reject(out.input.model_body,"MS01","missing MODEL command; Mplus omits MODEL only for automatic model families such as BASIC/EFA, outside project/grammar/mplus.md Not planned; write explicit BY, ON or variance statements instead");
      return std::unexpected(*error);
    }
    lex();
    // Discover factor order without interpreting forward references as observed names.
    for (std::size_t begin = 0; begin < tokens.size();) {
      auto end = begin; while (end < tokens.size() && tokens[end].text != ";") ++end;
      bool deferred = false;
      for (auto i = begin; i < end; ++i) if (tokens[i].text == "|" || tokens[i].text == "{" || tokens[i].text == "$" || tokens[i].text == "#" || tokens[i].text == "%" || tokens[i].text == "~") deferred = true;
      for (auto i = begin; !deferred && i < end; ++i) if (tokens[i].text == "by") {
        if (i != begin + 1) { reject(tokens[begin].span,"MS09","left-hand BY lists or ranges define ESEM factor sets; ESEM is outside scope; write one factor per BY statement instead"); break; }
        for (auto j = begin; j < i; ++j) if (tokens[j].text != "-") {
          if (tokens[j].text.empty() || !(tokens[j].text.front() >= 'a' && tokens[j].text.front() <= 'z') || !std::all_of(tokens[j].text.begin(),tokens[j].text.end(),[](char c) {return (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_';})) { reject(tokens[j].span,"NM01","invalid BY factor name '"+tokens[j].text+"'; Mplus requires a letter followed by letters, digits or underscores; write a valid factor name instead"); break; }
          if (observed_set.contains(tokens[j].text)) { reject(tokens[j].span,"MS03","BY factor '"+tokens[j].text+"' is an observed analysis name; Mplus requires a distinct factor name; rename the factor"); break; }
          if (!is_latent(tokens[j].text)) { latent.push_back(tokens[j].text); latent_set.insert(tokens[j].text); spelling[tokens[j].text] = out.input.source.substr(tokens[j].span.begin, tokens[j].span.end-tokens[j].span.begin); }
        }
        break;
      }
      begin = end+1;
    }
    for(std::size_t begin=0;begin<tokens.size();) {
      auto end=begin;while(end<tokens.size() && tokens[end].text!=";") ++end;
      auto bar=begin;while(bar<end && tokens[bar].text!="|") ++bar;
      if(bar<end) for(auto j=begin;j<bar;++j) {
        const auto& t=tokens[j];
        if(t.text.empty() || !(t.text.front()>='a' && t.text.front()<='z') || observed_set.contains(t.text)) {reject(t.span,"GR01","growth factor must be a distinct latent name; rename the factor instead");return std::unexpected(*error);}
        if(!is_latent(t.text)) {latent.push_back(t.text);latent_set.insert(t.text);spelling[t.text]=out.input.source.substr(t.span.begin,t.span.end-t.span.begin);}
      }
      begin=end+1;
    }
    for(std::size_t begin=0;begin<tokens.size();) {
      auto end=begin;while(end<tokens.size() && tokens[end].text!=";") ++end;
      growth(std::vector<Token>(tokens.begin()+static_cast<std::ptrdiff_t>(begin),tokens.begin()+static_cast<std::ptrdiff_t>(end)));
      if(error) return std::unexpected(*error);
      begin=end+1;
    }
    std::vector<Token> current;
    for (const auto& token : tokens) { if (token.text == ";") { statement(current); current.clear(); } else current.push_back(token); if (error) return std::unexpected(*error); }
    if (!current.empty() && std::any_of(current.begin(),current.end(),[](const Token& token) {return token.text == "%";})) { statement(current); if (error) return std::unexpected(*error); }
    if (!current.empty()) { reject(current.front().span,"MS01","MODEL statement has no ';'; Mplus requires a terminator; add ';'"); return std::unexpected(*error); }
    if (!category_counts.empty()) {
      if (category_counts.size()!=out.input.categorical.size()) {
        reject(out.input.model_body,"CT01","category schema does not match CATEGORICAL; supply counts in CATEGORICAL order instead");return std::unexpected(*error);
      }
      for(std::size_t j=0;j<category_counts.size();++j) {
        const auto name=lower(out.input.categorical[j]);const int n=category_counts[j];
        if(n<2 || n>10) {reject(out.input.model_body,"CT01","categorical outcome needs two through ten categories, as in Mplus; recode the data instead");return std::unexpected(*error);}
        for(const auto& row:rows) if(row.op==Op::Threshold && row.lhs==name) {
          int index=0;std::from_chars(row.rhs.data()+1,row.rhs.data()+row.rhs.size(),index);
          if(index>=n) {reject(row.span,"CT02","threshold index exceeds the data's categories; remove the threshold or supply the missing categories instead");return std::unexpected(*error);}
        }
        for(int k=1;k<n;++k) put({name,"t"+std::to_string(k),growth_outcomes.contains(name) ? "gr_threshold_"+std::to_string(k) : "",Op::Threshold,{},{},out.input.model_body},false);
      }
    }
    std::set<std::string> x;
    for (const auto& name : observed) if (predictors.contains(name) && !dependent.contains(name)) x.insert(name);
    std::set<std::string> mentioned_x;
    for (const auto& name : observed) if (x.contains(name))
      out.input.observed_x.push_back(spelling.at(name));
    for (const auto& row : rows) if (row.op == Op::Covariance || row.op == Op::Intercept) {
      if (x.contains(row.lhs)) mentioned_x.insert(row.lhs);
      if (x.contains(row.rhs)) mentioned_x.insert(row.rhs);
    }
    if (!mentioned_x.empty() && mentioned_x != x) {
      std::string completion;
      for (const auto& name : out.input.observed_x) completion += (completion.empty() ? "" : " ") + name;
      reject(out.input.model_body,"MS08","partial observed independent moments give mixed conditioning; complete the joint model by adding `"+completion+";` to MODEL, or remove all x moment mentions instead");
      return std::unexpected(*error);
    }
    out.input.joint_x = !mentioned_x.empty();
    if (out.input.joint_x) {
      for (const auto& name : x) {
        put({name,name,"",Op::Covariance,{},{},out.input.model_body},false);
        if (!out.input.nomeanstructure) put({name,"","",Op::Intercept,{},{},out.input.model_body},false);
      }
      if (!out.input.nocovariances) for (auto a=x.begin(); a!=x.end(); ++a)
        for (auto b=std::next(a); b!=x.end(); ++b)
          put({*a,*b,"",Op::Covariance,{},{},out.input.model_body},false);
    }
    auto all = observed; all.insert(all.end(),latent.begin(),latent.end());
    for (const auto& name : all) if (!x.contains(name)) {
      put({name,name,"",Op::Covariance,is_categorical(name) ? std::optional<double>{1} : std::nullopt,{},out.input.model_body},false);
      if (is_categorical(name)) put({name,name,"",Op::ResponseScale,1,{},out.input.model_body},false);
      if (!out.input.nomeanstructure) put({name,"","",Op::Intercept,(is_latent(name) || is_categorical(name)) ? std::optional<double>{0} : std::nullopt,{},out.input.model_body},false);
      if (!is_latent(name) && !dependent.contains(name) && !predictors.contains(name)) out.notes.push_back({MplusClass::Reported,out.input.model_body,"DF07","analysis variable '"+name+"' is uncorrelated with all other variables, as in Mplus"});
    }
    std::vector<std::string> exogenous, finals;
    for (const auto& name : all) {
      if (is_latent(name) && !dependent.contains(name)) exogenous.push_back(name);
      if (dependent.contains(name) && !predictors.contains(name) && !indicators.contains(name)) finals.push_back(name);
    }
    if (!out.input.nocovariances) for (const auto& family : {exogenous,finals}) for (std::size_t a = 0; a < family.size() && !error; ++a) for (std::size_t b = a+1; b < family.size() && !error; ++b) {
      const auto& l = family[a]; const auto& r = family[b];
      const auto exo = [&](const auto& n) { return is_latent(n) && !dependent.contains(n); };
      const auto final = [&](const auto& n) { return dependent.contains(n) && !predictors.contains(n) && !indicators.contains(n); };
      if ((exo(l) && exo(r)) || (final(l) && final(r))) put({l,r,"",Op::Covariance,{},{},out.input.model_body},false);
    }
    if (error) return std::unexpected(*error);
    if (!out.input.groups.empty()) {expand_groups();if(error) return std::unexpected(*error);}
    for (const auto& name:observed) if(is_categorical(name)) {
      if(!dependent.contains(name)) {reject(out.input.model_body,"CT07","CATEGORICAL variable '"+name+"' is not dependent; Mplus requires categorical outcomes; remove it from CATEGORICAL or model it as an outcome instead");return std::unexpected(*error);}
      if(out.input.parameterization=="DELTA" && predictors.contains(name)) {reject(out.input.model_body,"CT05","categorical outcome '"+name+"' both influences and is influenced; Mplus requires THETA; use PARAMETERIZATION = THETA instead");return std::unexpected(*error);}
    }
    constraints(); if(error) return std::unexpected(*error);
    indirects(); if(error) return std::unexpected(*error);
    // Resolve names only after role/default calculations; labels remain case-folded.
    for (auto& row : rows) {
      if(row.op==Op::Threshold && !category_counts.empty()) {
        const auto name=std::find_if(out.input.categorical.begin(),out.input.categorical.end(),[&](const auto& n){return lower(n)==row.lhs;});
        int index=0;std::from_chars(row.rhs.data()+1,row.rhs.data()+row.rhs.size(),index);
        if(name!=out.input.categorical.end() && index>=category_counts[static_cast<std::size_t>(name-out.input.categorical.begin())]) {
          reject(row.span,"CT02","threshold index exceeds the data's categories; remove the threshold instead");return std::unexpected(*error);
        }
      }
      if(row.op==Op::AuxiliaryParam) continue;
      row.lhs = spelling.at(row.lhs);
      if (!row.rhs.empty() && row.op!=Op::Threshold) row.rhs = spelling.at(row.rhs);
    }
    for (auto& group:grouped_rows) for (auto& row:group) {
      if(row.op==Op::AuxiliaryParam) continue;
      row.lhs=spelling.at(row.lhs);if(!row.rhs.empty() && row.op!=Op::Threshold) row.rhs=spelling.at(row.rhs);
    }
    for (std::size_t g=0;g<grouped_rows.size();++g) for (const auto& row:grouped_rows[g])
      if (row.span.end==0 || row.span.begin==out.input.model_body.begin)
        out.generated_rows.push_back({row.lhs,row.rhs,row.op,static_cast<std::int32_t>(g+1)});
    if (grouped_rows.empty()) for (const auto& row:rows) if(row.span.begin==out.input.model_body.begin)
      out.generated_rows.push_back({row.lhs,row.rhs,row.op,1});
    auto& flat = out.flat;
    flat.source_text.assign(out.input.source.begin(),out.input.source.end());
    std::map<std::string,std::size_t> offsets;
    for (const auto& row : rows) for (const auto* value : {&row.lhs,&row.rhs,&row.label}) if (!offsets.contains(*value)) { offsets[*value] = flat.symbol_text.size(); flat.symbol_text.insert(flat.symbol_text.end(),value->begin(),value->end()); flat.symbol_text.push_back('\0'); }
    for (const auto& group:grouped_rows) for (const auto& row:group) if (!offsets.contains(row.label)) {offsets[row.label]=flat.symbol_text.size();flat.symbol_text.insert(flat.symbol_text.end(),row.label.begin(),row.label.end());flat.symbol_text.push_back('\0');}
    const auto view = [&](const auto& s) { return std::string_view(flat.symbol_text.data()+offsets.at(s),s.size()); };
    if (!grouped_rows.empty()) {
      for (std::size_t i=0;i<rows.size();++i) {
        GroupVec values, starts;bool any_start=false;
        for (const auto& group:grouped_rows) {
          const auto& row=group[i];
          if(row.fixed) values.per_group.push_back(FixedValue{*row.fixed});
          else if(!row.label.empty()) values.per_group.push_back(Label{view(row.label)});
          else values.per_group.push_back(Free{});
          if(row.start && !row.fixed) {starts.per_group.push_back(StartValue{*row.start});any_start=true;} else starts.per_group.push_back(Free{});
        }
        const auto& row=rows[i];
        if(any_start) flat.rows.push_back({view(row.lhs),row.op,view(row.rhs),1,flat.add_modifier(std::move(starts)),row.span});
        flat.rows.push_back({view(row.lhs),row.op,view(row.rhs),1,flat.add_modifier(std::move(values)),row.span});
      }
      if(!append_expressions()) return std::unexpected(*error);
      return std::move(out);
    }
    for (const auto& row : rows) {
      std::uint32_t mod = 0;
      if (row.fixed) mod = flat.add_modifier(FixedValue{*row.fixed});
      else if (!row.label.empty() && row.start) {
        mod = flat.add_modifier(StartValue{*row.start});
        flat.rows.push_back({view(row.lhs),row.op,view(row.rhs),1,mod,row.span});
        mod = flat.add_modifier(Label{view(row.label)});
      }
      else if (!row.label.empty()) mod = flat.add_modifier(Label{view(row.label)});
      else if (row.start) mod = flat.add_modifier(StartValue{*row.start});
      flat.rows.push_back({view(row.lhs),row.op,view(row.rhs),1,mod,row.span});
    }
    if(!append_expressions()) return std::unexpected(*error);
    return std::move(out);
  }
};
}
// production: model_body ::= model_statement*
parse_expected<MplusModel> MplusParser::parse(std::string_view source) {
  auto input = read(source); if (!input) return std::unexpected(input.error());
  return Lowerer(std::move(*input)).run();
}
}

namespace magmaan::parse {
// production: model_body ::= model_statement*
parse_expected<MplusModel> MplusParser::parse_ordinal(std::string_view source,
    const std::vector<std::int32_t>& category_counts) {
  auto input=read(source);if(!input) return std::unexpected(input.error());
  Lowerer lowerer(std::move(*input));lowerer.category_counts=category_counts;
  return lowerer.run();
}
}
