// @generated by r-package/tools/vendor-cpp.sh from cpp/src/util/version.cpp — DO NOT EDIT; re-run `just vendor`.
#include "magmaan/version.hpp"

namespace magmaan {

std::string_view version() noexcept {
  return "0.0.1";
}

}
