// @generated by dev/vendor-cpp.sh from include/magmaan/estimate/diagnostics.hpp — DO NOT EDIT; re-run `just vendor`.
#pragma once

#include <cstdint>
#include <vector>

#include <Eigen/Core>

#include "magmaan/estimate/bounds.hpp"  // Bounds, ActiveBoundDiagnostics

// Fit finalization audit (Layer 2).
//
// L1 (`optim::audit_terminal_iterate`) certifies first-order stationarity in
// the *driven* coordinate system the optimizer minimized over. L2 lives on the
// other side of `prob.expand(out->x)`: it operates on full θ and answers a
// different question — "is this fit usable for downstream inference?" — by
// recording diagnostics that SE/χ²/robust-correction code needs to decide
// whether its formulae apply. L2 never blocks a fit; it records.
//
// Concretely:
//   - Implied-Σ positive-definiteness per group. ML/GLS need Σ⁻¹; ULS does
//     not. Consumers decide what they need.
//   - Linear equality constraint residual. The K-reparameterization is exact
//     in the pure-merge case (residual to roundoff) and tiny under
//     general-linear constraints. A non-tiny residual means the expansion
//     itself is broken — a hard correctness signal worth surfacing.
//   - Nonlinear equality constraint residual at θ̂. IPOPT drives
//     `h(θ̂) → 0`; recording the achieved infinity-norm tells the user
//     whether the nonlinear-constraint solve actually converged.
//   - Active-bound set on the FULL expanded θ — this is the Heywood-case
//     detector: a variance parameter at its 0 bound has a one-sided
//     derivative, and the standard info-matrix SE for it is not valid.
//
// Forward-declarations keep the header light; the cpp pulls in the model and
// constraint headers it actually needs.

namespace magmaan::model {
class ModelEvaluator;
}
namespace magmaan::spec {
struct LatentStructure;
}
namespace magmaan::estimate {
struct EqConstraints;
struct NonlinearEqConstraints;
}

namespace magmaan::estimate {

// Admissibility of one assembled covariance matrix. `block` and every row
// index are 0-based in C++; the R boundary converts them to 1-based indices.
// `covariance_rows` contains every source partable row that writes this matrix
// block, so a failed joint PSD check remains traceable even when no individual
// variance or correlation explains the failure.
struct CovarianceBlockDiagnostics {
  std::int32_t             block = -1;
  double                   min_eigenvalue = 0.0;
  bool                     finite = true;
  bool                     psd = true;
  bool                     positive_definite = true;
  std::vector<std::int32_t> covariance_rows;
  std::vector<std::int32_t> negative_variance_rows;
  std::vector<std::int32_t> invalid_correlation_rows;
};

// Estimator-neutral post-fit covariance admissibility. The primitive
// reduced-LISREL covariance matrices are Ψ (latent innovations/disturbances)
// and Θ (observed residuals). They are admissible when PSD; the implied
// observed Σ must additionally be PD for the ordinary Gaussian likelihood.
//
// Singular-but-PSD Ψ/Θ blocks remain admissible covariance matrices. Their
// `positive_definite` field is false so consumers can identify boundary cases
// without conflating them with an indefinite matrix.
struct AdmissibilityDiagnostics {
  bool checked = false;
  bool covariance_matrices_psd = false;
  bool implied_sigma_pd = false;
  bool admissible = false;
  std::vector<CovarianceBlockDiagnostics> theta_blocks;
  std::vector<CovarianceBlockDiagnostics> psi_blocks;
};

// First-order stationarity in the ordinary full-model representation. Unlike
// `optim::TerminalAudit`, this diagnostic never sees optimizer-driven or
// Cholesky coordinates. It measures the objective differential against the
// tangent/normal geometry of the original linear equalities, nonlinear-
// equality tangent space, box bounds, and primitive PSD covariance cones.
//
// The scalar residual still needs a metric. `model_frobenius` is the product
// Frobenius metric induced by the LISREL matrices: symmetric off-diagonal
// covariance entries receive weight 2, ordinary matrix/vector entries weight
// 1, and repeated/shared coordinates accumulate their contributions. This is
// invariant to a change of parameter basis when the metric is transformed
// with the model map, and to orthogonal changes of basis within covariance
// blocks. It is deliberately not advertised as invariant to arbitrary changes
// of measurement units.
struct GeometricStationarityDiagnostics {
  bool checked = false;
  bool gradient_finite = false;
  bool feasible = false;
  bool covariance_feasible = false;

  // Equality/bound normal cone only. This is the common-full-model companion
  // to the driven/lavaan-compatible audit and excludes PSD normal multipliers.
  // The stationary verdict thresholds the metric-dual L2 residual; the
  // coordinatewise infinity norm is retained only as a familiar readout.
  bool ambient_stationary = false;
  double ambient_residual_inf = -1.0;
  double ambient_residual_l2 = -1.0;

  // Equality/bound normals plus the true PSD-cone normals in the null spaces
  // of singular primitive covariance blocks.
  bool cone_stationary = false;
  double cone_residual_inf = -1.0;
  double cone_residual_l2 = -1.0;

  double raw_gradient_inf = -1.0;
  double stationarity_tol = 1e-3;
  double covariance_eigen_tol = 1e-8;
  std::int32_t covariance_active_blocks = 0;
  std::int32_t covariance_nullity = 0;

  bool ambient_projection_converged = false;
  bool cone_projection_converged = false;
  std::int32_t ambient_projection_iterations = 0;
  std::int32_t cone_projection_iterations = 0;
};

struct FitDiagnostics {
  // Implied Σ Cholesky per group; `sigma_pd_all` is the && over the vector.
  // ML/GLS need PD; ULS only needs finite. Empty when the evaluator could
  // not compute Σ at all (e.g. non-finite θ propagated through model
  // evaluation) — `sigma_pd_all` then defaults to false.
  std::vector<bool>      sigma_pd_per_block;
  bool                   sigma_pd_all = false;

  // Linear equality constraint residual at θ̂ = max |(A_eq · θ - b_eq)_k|.
  // 0 when the model has no linear equality constraints (`EqConstraints::active() == false`).
  double                 lin_eq_residual_inf = 0.0;
  bool                   lin_eq_satisfied    = true;

  // Nonlinear equality constraint residual at θ̂ = h(θ̂). Empty when there
  // are no nonlinear constraints. `_inf` is the infinity-norm; `_satisfied`
  // is `_inf <= nl_eq_residual_tol`.
  Eigen::VectorXd        nl_eq_residual;
  double                 nl_eq_residual_inf  = 0.0;
  bool                   nl_eq_satisfied     = true;

  // Which expanded-θ coordinates sit on a finite bound (the Heywood-case
  // diagnostic). Empty when `bounds.empty()` or no parameter is active.
  ActiveBoundDiagnostics active_bounds_full;

  // Covariance-domain audit on the assembled reduced-LISREL matrices.
  AdmissibilityDiagnostics admissibility;

  // Additive common-coordinate / PSD-cone stationarity diagnostic. It remains
  // unchecked on fit paths that have not supplied an ordinary full-θ
  // objective gradient; `fit$audit` is never overwritten.
  GeometricStationarityDiagnostics geometric_stationarity;

  // SNLLS-only: did the gp expand take the affine fallback `θ₀ + K_β·β`
  // because `profiled(β)` returned an error? v1 leaves this `false` —
  // wiring it requires a flag on `GpProblem`. Recorded here so consumers
  // (and a follow-up PR) have a stable schema slot.
  bool                   snlls_profile_fallback = false;
};

struct DiagnosticsOptions {
  // Active-bound coordinate tolerance — matches the existing
  // `estimate::active_bounds` default (a parameter is "active" if it sits
  // within `1e-6` of a finite bound).
  double active_bound_tol    = 1e-6;
  // The K reparameterization is exact under pure-merge constraints and at
  // worst orthonormal-roundoff under general-linear ones. A residual
  // exceeding 1e-8 is a correctness signal that the expansion machinery,
  // not the optimizer, is misbehaving.
  double lin_eq_residual_tol = 1e-8;
  // Nonlinear equality feasibility target.
  double nl_eq_residual_tol  = 1e-6;
  // Scale-relative tolerances for declaring a symmetric covariance matrix
  // PSD/PD, a variance negative, or a defined correlation outside [-1, 1].
  double covariance_eigen_tol = 1e-8;
  double variance_tol         = 1e-8;
  double correlation_tol      = 1e-8;
};

struct GeometricStationarityOptions {
  double stationarity_tol = 1e-3;
  double covariance_eigen_tol = 1e-8;
  double equality_tol = 1e-6;
  double active_bound_tol = 1e-8;
  double projection_tol = 1e-11;
  std::int32_t projection_max_iter = 20000;
};

// Audit a terminal full-θ objective gradient against the original model
// geometry. This is public so research code can recompute the geometric audit
// with alternative gradients or tolerances without rerunning an optimizer.
GeometricStationarityDiagnostics
audit_geometric_stationarity(
    const Eigen::VectorXd& theta_full,
    const Eigen::VectorXd& gradient_full,
    const spec::LatentStructure& pt,
    const model::ModelEvaluator& ev,
    const EqConstraints& con,
    const NonlinearEqConstraints& nl,
    const Bounds& bounds,
    GeometricStationarityOptions opts = {});

// Build a FitDiagnostics from an expanded θ and the prelude bits the fit
// path already carried. Never errors — every check that cannot be performed
// (no bounds, no constraints, no nonlinear block, evaluator error) records a
// benign default that downstream consumers can read uniformly.
//
// `snlls_profile_fallback_flag` is wired only from the SNLLS expand site
// (v1: always `false` — see `FitDiagnostics::snlls_profile_fallback`).
FitDiagnostics
finalize_fit_diagnostics(const Eigen::VectorXd&        theta_full,
                         const model::ModelEvaluator&  ev,
                         const EqConstraints&          con,
                         const NonlinearEqConstraints& nl,
                         const Bounds&                 bounds,
                         bool                          snlls_profile_fallback_flag = false,
                         DiagnosticsOptions            opts = {});

// Row-aware overload used by fit composers. The numeric audit is identical to
// the compatibility overload above, but source rows are populated from `pt`.
FitDiagnostics
finalize_fit_diagnostics(const Eigen::VectorXd&        theta_full,
                         const spec::LatentStructure&  pt,
                         const model::ModelEvaluator&  ev,
                         const EqConstraints&          con,
                         const NonlinearEqConstraints& nl,
                         const Bounds&                 bounds,
                         bool                          snlls_profile_fallback_flag = false,
                         DiagnosticsOptions            opts = {});

}  // namespace magmaan::estimate
