// @generated by dev/vendor-cpp.sh from src/estimate/diagnostics.cpp — DO NOT EDIT; re-run `just vendor`.
#include "magmaan/estimate/diagnostics.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <utility>

#include <Eigen/Cholesky>
#include <Eigen/Core>
#include <Eigen/Eigenvalues>

#include "magmaan/estimate/bounds.hpp"          // active_bounds
#include "magmaan/estimate/constraints.hpp"     // EqConstraints
#include "magmaan/estimate/nl_constraints.hpp"  // NonlinearEqConstraints
#include "magmaan/model/matrix_rep.hpp"
#include "magmaan/model/model_evaluator.hpp"    // sigma, ImpliedMoments
#include "magmaan/spec/partable.hpp"

namespace magmaan::estimate {

namespace {

double matrix_scale(const Eigen::MatrixXd& M) {
  if (M.size() == 0 || !M.allFinite()) return 1.0;
  return std::max(1.0, M.cwiseAbs().maxCoeff());
}

CovarianceBlockDiagnostics
audit_covariance_block(const Eigen::MatrixXd& M, model::MatId mat,
                       std::int32_t block,
                       const spec::LatentStructure* pt,
                       const model::MatrixRep& rep,
                       DiagnosticsOptions opts) {
  CovarianceBlockDiagnostics out;
  out.block = block;

  if (M.rows() == 0 || M.cols() != M.rows() || !M.allFinite()) {
    out.finite = false;
    out.psd = false;
    out.positive_definite = false;
    out.min_eigenvalue = std::numeric_limits<double>::quiet_NaN();
  } else {
    const Eigen::MatrixXd Sym = 0.5 * (M + M.transpose());
    Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> eig(
        Sym, Eigen::EigenvaluesOnly);
    if (eig.info() != Eigen::Success || !eig.eigenvalues().allFinite()) {
      out.finite = false;
      out.psd = false;
      out.positive_definite = false;
      out.min_eigenvalue = std::numeric_limits<double>::quiet_NaN();
    } else {
      out.min_eigenvalue = eig.eigenvalues().minCoeff();
      const double tol = opts.covariance_eigen_tol * matrix_scale(Sym);
      out.psd = out.min_eigenvalue >= -tol;
      out.positive_definite = out.min_eigenvalue > tol;
    }
  }

  if (pt == nullptr || rep.cell_for_row.size() != pt->size() ||
      M.rows() == 0 || M.cols() != M.rows()) {
    return out;
  }

  double diag_scale = 1.0;
  if (M.diagonal().size() > 0 && M.diagonal().allFinite()) {
    diag_scale = std::max(1.0, M.diagonal().cwiseAbs().maxCoeff());
  }
  const double variance_tol = opts.variance_tol * diag_scale;

  for (std::size_t i = 0; i < pt->size(); ++i) {
    const model::Cell& cell = rep.cell_for_row[i];
    if (!cell.used || cell.mat != mat || cell.block != block ||
        cell.row < 0 || cell.col < 0 || cell.row >= M.rows() ||
        cell.col >= M.cols()) {
      continue;
    }
    const auto row = static_cast<std::int32_t>(i);
    out.covariance_rows.push_back(row);
    if (cell.row == cell.col) {
      const double variance = M(cell.row, cell.col);
      if (!std::isfinite(variance) || variance < -variance_tol) {
        out.negative_variance_rows.push_back(row);
      }
      continue;
    }

    const double va = M(cell.row, cell.row);
    const double vb = M(cell.col, cell.col);
    const double covariance = M(cell.row, cell.col);
    if (!std::isfinite(va) || !std::isfinite(vb) ||
        !std::isfinite(covariance)) {
      out.invalid_correlation_rows.push_back(row);
      continue;
    }
    // A correlation is defined only for strictly positive variances. Zero
    // variance paired with nonzero covariance is caught by the joint PSD test.
    if (va > variance_tol && vb > variance_tol) {
      const double correlation = covariance / std::sqrt(va * vb);
      if (!std::isfinite(correlation) ||
          std::abs(correlation) > 1.0 + opts.correlation_tol) {
        out.invalid_correlation_rows.push_back(row);
      }
    }
  }
  return out;
}

AdmissibilityDiagnostics
audit_admissibility(const Eigen::VectorXd& theta_full,
                    const spec::LatentStructure* pt,
                    const model::ModelEvaluator& ev,
                    bool implied_sigma_pd,
                    DiagnosticsOptions opts) {
  AdmissibilityDiagnostics out;
  out.implied_sigma_pd = implied_sigma_pd;

  auto matrices = ev.assembled(theta_full);
  if (!matrices.has_value()) return out;

  out.checked = true;
  out.covariance_matrices_psd = true;
  const model::MatrixRep& rep = ev.matrix_rep();
  out.theta_blocks.reserve(matrices->blocks.size());
  out.psi_blocks.reserve(matrices->blocks.size());
  for (std::size_t b = 0; b < matrices->blocks.size(); ++b) {
    const auto block = static_cast<std::int32_t>(b);
    auto theta = audit_covariance_block(
        matrices->blocks[b].Theta, model::MatId::Theta, block, pt, rep, opts);
    if (!theta.psd) out.covariance_matrices_psd = false;
    out.theta_blocks.push_back(std::move(theta));

    if (matrices->blocks[b].Psi.size() > 0) {
      auto psi = audit_covariance_block(
          matrices->blocks[b].Psi, model::MatId::Psi, block, pt, rep, opts);
      if (!psi.psd) out.covariance_matrices_psd = false;
      out.psi_blocks.push_back(std::move(psi));
    }
  }
  out.admissible =
      out.checked && out.covariance_matrices_psd && out.implied_sigma_pd;
  return out;
}

FitDiagnostics
finalize_fit_diagnostics_impl(const Eigen::VectorXd&        theta_full,
                              const spec::LatentStructure*  pt,
                              const model::ModelEvaluator&  ev,
                              const EqConstraints&          con,
                              const NonlinearEqConstraints& nl,
                              const Bounds&                 bounds,
                              bool snlls_profile_fallback_flag,
                              DiagnosticsOptions opts) {
  FitDiagnostics d;
  d.snlls_profile_fallback = snlls_profile_fallback_flag;

  // --- Implied-Σ positive-definiteness per group ------------------------
  // Reuses the pattern from src/measures/fit_measures.cpp:130-135 — LLT on
  // the symmetrized matrix; the symmetrize step is conservative because Σ(θ)
  // is mathematically symmetric but its numerical realisation can pick up
  // roundoff asymmetry that nudges LLT to spurious failure.
  auto moments = ev.sigma(theta_full);
  if (!moments.has_value()) {
    // Evaluator could not produce Σ at all (non-finite θ, etc.). Leave the
    // per-block vector empty and the `_all` flag false — consumers reading
    // either field see the absence.
    d.sigma_pd_all = false;
  } else {
    const auto& sig = moments->sigma;
    d.sigma_pd_per_block.reserve(sig.size());
    bool all_pd = !sig.empty();
    for (const auto& Sigma : sig) {
      const Eigen::MatrixXd Sym = 0.5 * (Sigma + Sigma.transpose());
      Eigen::LLT<Eigen::MatrixXd> llt(Sym);
      const bool pd = (llt.info() == Eigen::Success);
      d.sigma_pd_per_block.push_back(pd);
      if (!pd) all_pd = false;
    }
    d.sigma_pd_all = all_pd;
  }

  d.admissibility =
      audit_admissibility(theta_full, pt, ev, d.sigma_pd_all, opts);

  // --- Linear equality constraint residual ------------------------------
  // The K-reparameterization enforces `A_eq · θ = b_eq` by construction
  // (`θ = θ₀ + K·α` with `K` in ker(A_eq)); the residual at θ̂ should be
  // either 0 (pure-merge K) or orthonormal roundoff (general-linear). A
  // residual exceeding `lin_eq_residual_tol` indicates the expansion itself
  // is misbehaving — not the optimizer.
  if (con.active() && con.A_eq.rows() > 0 && con.A_eq.cols() == theta_full.size()) {
    const Eigen::VectorXd r = con.A_eq * theta_full - con.b_eq;
    d.lin_eq_residual_inf = r.cwiseAbs().maxCoeff();
    d.lin_eq_satisfied    = d.lin_eq_residual_inf <= opts.lin_eq_residual_tol;
  }
  // No active linear constraints ⇒ residual is 0, satisfied is true (defaults).

  // --- Nonlinear equality constraint residual ---------------------------
  // IPOPT drives `h(θ̂) → 0`; recording the achieved infinity-norm tells the
  // user whether the nonlinear-constraint solve actually converged.
  // `nl.h()` is sized to `nl.m()`, which `active() == false` reports as 0 —
  // we still evaluate so `nl_eq_residual` is well-defined as the empty vector.
  if (nl.active() && nl.npar == theta_full.size()) {
    d.nl_eq_residual = nl.h(theta_full);
    if (d.nl_eq_residual.size() > 0) {
      d.nl_eq_residual_inf = d.nl_eq_residual.cwiseAbs().maxCoeff();
    }
    d.nl_eq_satisfied = d.nl_eq_residual_inf <= opts.nl_eq_residual_tol;
  }

  // --- Active-bound diagnostic on full θ --------------------------------
  // Reuses estimate::active_bounds(). An empty `bounds` reports nothing
  // active; that's the desired default. The function returns a
  // `post_expected` to be uniform with the rest of the post-fit machinery,
  // but the only error path here would be a size mismatch (caught by the
  // fit composer long before we get here) — we treat any error as "no
  // active bounds recorded" rather than failing the audit.
  auto ab = active_bounds(theta_full, bounds, opts.active_bound_tol);
  if (ab.has_value()) {
    d.active_bounds_full = std::move(*ab);
  }

  return d;
}

}  // namespace

FitDiagnostics
finalize_fit_diagnostics(const Eigen::VectorXd&        theta_full,
                         const model::ModelEvaluator&  ev,
                         const EqConstraints&          con,
                         const NonlinearEqConstraints& nl,
                         const Bounds&                 bounds,
                         bool                          snlls_profile_fallback_flag,
                         DiagnosticsOptions            opts) {
  return finalize_fit_diagnostics_impl(
      theta_full, nullptr, ev, con, nl, bounds,
      snlls_profile_fallback_flag, opts);
}

FitDiagnostics
finalize_fit_diagnostics(const Eigen::VectorXd&        theta_full,
                         const spec::LatentStructure&  pt,
                         const model::ModelEvaluator&  ev,
                         const EqConstraints&          con,
                         const NonlinearEqConstraints& nl,
                         const Bounds&                 bounds,
                         bool                          snlls_profile_fallback_flag,
                         DiagnosticsOptions            opts) {
  return finalize_fit_diagnostics_impl(
      theta_full, &pt, ev, con, nl, bounds,
      snlls_profile_fallback_flag, opts);
}

}  // namespace magmaan::estimate
