// @generated by r-package/tools/vendor-cpp.sh from cpp/src/estimate/fiml_gamma.cpp — DO NOT EDIT; re-run `just vendor`.
#include "fiml_internal.hpp"

namespace magmaan::estimate::fiml {
namespace internal {
// === Analytic ML2S missing-data Γ-influence ================================
//
// The Stage-1 saturated-FIML sandwich Γ_b = n·H⁻¹JH⁻¹ feeds the non-NT Stage-2
// weight (DWLS/ADF/DLS); the estimated-weight IJ correction needs the per-case
// influence dΓ_b/dw_i. Writing θ = (μ, vech Σ), with s_j the deviance score
// (row j of `fiml_saturated_scores_block`) and g_j = −½ s_j the log-likelihood
// gradient, the weighted saturated fit has
//   H = (n/2)·H̄_dev = Σ_j w_j I_j   (total observed info; I_j = ½ per-case
//                                     deviance Hessian)
//   J = ¼ Σ_j w_j s_j s_jᵀ = Σ_j w_j g_j g_jᵀ      Γ = n·H⁻¹JH⁻¹
// and the saturated-moment influence is Δθ_i = H⁻¹ g_i (= `saturated_em_moment_
// influence` row i). The total weight-derivative is direct (explicit weight on
// case i) plus the θ-movement of the fit:
//   dH/dw_i = I_i + (∂H/∂θ)·Δθ_i ,   dJ/dw_i = g_i g_iᵀ + (∂J/∂θ)·Δθ_i
//   dΓ/dw_i = H⁻¹JH⁻¹·(dn/dw_i = 1)
//           + n·[ −H⁻¹(dH)H⁻¹JH⁻¹ + H⁻¹(dJ)H⁻¹ − H⁻¹JH⁻¹(dH)H⁻¹ ].
// The J-movement collapses without any per-case info matrix:
//   (∂J/∂θ)·v = ¼ (dSᵀ S + Sᵀ dS) ,  dS = directional deviance score along v.
// The H-movement is the per-pattern directional third derivative of the
// analytic saturated Hessian. `weighted_two_stage_gamma_influence_fd_block`
// multiplies its central difference by n, so this returns n·dΓ/dw_i to match it.

// ∂s/∂θ·v for the deviance scores: directional twin of
// `fiml_saturated_scores_block` along v = (dmu, dSigma).
post_expected<Eigen::MatrixXd>
fiml_saturated_scores_directional_block(const RawData& raw, std::size_t block,
                                        const Eigen::VectorXd& mu,
                                        const Eigen::MatrixXd& Sigma,
                                        const Eigen::VectorXd& dmu,
                                        const Eigen::MatrixXd& dSigma) {
  const Eigen::MatrixXd& X = raw.X[block];
  const Eigen::Index n = X.rows();
  const Eigen::Index p = X.cols();
  const Eigen::Index pstar = vech_len(p);
  Eigen::MatrixXd dscores = Eigen::MatrixXd::Zero(n, p + pstar);
  std::vector<Eigen::Index> obs;
  for (Eigen::Index r = 0; r < n; ++r) {
    obs.clear();
    obs.reserve(static_cast<std::size_t>(p));
    if (raw.mask.empty()) {
      for (Eigen::Index c = 0; c < p; ++c) obs.push_back(c);
    } else {
      for (Eigen::Index c = 0; c < p; ++c)
        if (raw.mask[block](r, c) != 0) obs.push_back(c);
    }
    if (obs.empty() || !finite_observed_row(X, obs, r)) {
      return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
          "ML2S Gamma influence: invalid observed row"));
    }
    const Eigen::Index q = static_cast<Eigen::Index>(obs.size());
    const Eigen::MatrixXd Sigma_o = select_square(Sigma, obs);
    Eigen::LLT<Eigen::MatrixXd> llt(Sigma_o);
    if (llt.info() != Eigen::Success) {
      return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
          "ML2S Gamma influence: Sigma_oo is not positive definite"));
    }
    const Eigen::MatrixXd A = llt.solve(Eigen::MatrixXd::Identity(q, q));
    const Eigen::MatrixXd dS_o = select_square(dSigma, obs);
    const Eigen::VectorXd dmu_o = select_vector(dmu, obs);
    const Eigen::VectorXd Mu_o = select_vector(mu, obs);
    Eigen::VectorXd d(q);
    for (Eigen::Index j = 0; j < q; ++j) {
      d(j) = X(r, obs[static_cast<std::size_t>(j)]) - Mu_o(j);
    }
    const Eigen::VectorXd z = A * d;
    const Eigen::MatrixXd dA = -(A * dS_o * A);
    const Eigen::VectorXd dz = dA * d - A * dmu_o;  // dd/dθ·v = −dmu_o
    for (Eigen::Index i = 0; i < q; ++i) {
      dscores(r, obs[static_cast<std::size_t>(i)]) = -2.0 * dz(i);
    }
    // G = A − z zᵀ ⇒ dG = dA − (dz zᵀ + z dzᵀ); same vech packing as the base.
    const Eigen::MatrixXd dG =
        dA - (dz * z.transpose() + z * dz.transpose());
    for (Eigen::Index cj = 0; cj < q; ++cj) {
      const Eigen::Index c = obs[static_cast<std::size_t>(cj)];
      for (Eigen::Index ri = cj; ri < q; ++ri) {
        const Eigen::Index rr0 = obs[static_cast<std::size_t>(ri)];
        const Eigen::Index rr = std::max(rr0, c);
        const Eigen::Index cc = std::min(rr0, c);
        const Eigen::Index idx = p + vech_index(p, rr, cc);
        dscores(r, idx) += (ri == cj) ? dG(ri, cj) : 2.0 * dG(ri, cj);
      }
    }
  }
  return dscores;
}

// Per-case observed information I_i = ½·(case deviance Hessian), in the full
// q×q [μ; vech Σ] layout — the single-case slice of the analytic Hessian
// assembly (nr = 1, Zsum = z_i, M = z_i z_iᵀ).
post_expected<Eigen::MatrixXd>
fiml_saturated_case_info_block(const RawData& raw, std::size_t block,
                               Eigen::Index row, const Eigen::VectorXd& mu,
                               const Eigen::MatrixXd& Sigma) {
  const Eigen::MatrixXd& X = raw.X[block];
  const Eigen::Index p = X.cols();
  const Eigen::Index q = p + vech_len(p);
  std::vector<Eigen::Index> obs;
  obs.reserve(static_cast<std::size_t>(p));
  if (raw.mask.empty()) {
    for (Eigen::Index c = 0; c < p; ++c) obs.push_back(c);
  } else {
    for (Eigen::Index c = 0; c < p; ++c)
      if (raw.mask[block](row, c) != 0) obs.push_back(c);
  }
  if (obs.empty() || !finite_observed_row(X, obs, row)) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "ML2S Gamma influence: invalid observed row"));
  }
  const Eigen::Index m = static_cast<Eigen::Index>(obs.size());
  const Eigen::MatrixXd Sigma_o = select_square(Sigma, obs);
  Eigen::LLT<Eigen::MatrixXd> llt(Sigma_o);
  if (llt.info() != Eigen::Success) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "ML2S Gamma influence: Sigma_oo is not positive definite"));
  }
  Eigen::MatrixXd A = llt.solve(Eigen::MatrixXd::Identity(m, m));
  A = 0.5 * (A + A.transpose()).eval();
  const Eigen::VectorXd Mu_o = select_vector(mu, obs);
  Eigen::VectorXd d(m);
  for (Eigen::Index j = 0; j < m; ++j) {
    d(j) = X(row, obs[static_cast<std::size_t>(j)]) - Mu_o(j);
  }
  const Eigen::VectorXd Zsum = A * d;             // z_i (nr = 1)
  const Eigen::MatrixXd M = Zsum * Zsum.transpose();

  Eigen::MatrixXd H = Eigen::MatrixXd::Zero(q, q);
  for (Eigen::Index j = 0; j < m; ++j) {
    const Eigen::Index fj = obs[static_cast<std::size_t>(j)];
    for (Eigen::Index i = 0; i < m; ++i) {
      H(fj, obs[static_cast<std::size_t>(i)]) += 2.0 * A(i, j);
    }
  }
  std::vector<SigmaBasis> basis;
  basis.reserve(static_cast<std::size_t>(m * (m + 1) / 2));
  for (Eigen::Index cj = 0; cj < m; ++cj) {
    for (Eigen::Index ri = cj; ri < m; ++ri) {
      const Eigen::Index full_r0 = obs[static_cast<std::size_t>(ri)];
      const Eigen::Index full_c = obs[static_cast<std::size_t>(cj)];
      SigmaBasis e;
      e.full_index =
          p + vech_index(p, std::max(full_r0, full_c), std::min(full_r0, full_c));
      e.a = ri;
      e.b = cj;
      Eigen::VectorXd ADz =
          (ri == cj) ? Eigen::VectorXd(A.col(ri) * Zsum(ri))
                     : Eigen::VectorXd(A.col(ri) * Zsum(cj) +
                                       A.col(cj) * Zsum(ri));
      for (Eigen::Index i = 0; i < m; ++i) {
        const Eigen::Index full_i = obs[static_cast<std::size_t>(i)];
        const double h = 2.0 * ADz(i);
        H(full_i, e.full_index) += h;
        H(e.full_index, full_i) += h;
      }
      basis.push_back(e);
    }
  }
  for (std::size_t kk = 0; kk < basis.size(); ++kk) {
    const SigmaBasis& k = basis[kk];
    for (std::size_t ll = 0; ll <= kk; ++ll) {
      const SigmaBasis& l = basis[ll];
      const double h = -basis_trace_xy(A, A, l, k) +
                       basis_trace_xy(A, M, l, k) + basis_trace_xy(A, M, k, l);
      H(k.full_index, l.full_index) += h;
      if (kk != ll) H(l.full_index, k.full_index) += h;
    }
  }
  H = 0.5 * (H + H.transpose()).eval();  // deviance Hessian (nr = 1)
  return Eigen::MatrixXd(0.5 * H);       // I_i = ½ · deviance Hessian
}

// ∂(H̄_dev)/∂θ·v: per-pattern directional twin of
// `fiml_saturated_hessian_analytic_block` (pattern data moments held fixed).
// Caller scales by n/2 for the total-information derivative ∂H/∂θ·v.
post_expected<Eigen::MatrixXd>
fiml_saturated_hessian_directional_block(const FIMLCache& cache,
                                         std::size_t block,
                                         const Eigen::VectorXd& mu,
                                         const Eigen::MatrixXd& Sigma,
                                         const Eigen::VectorXd& dmu,
                                         const Eigen::MatrixXd& dSigma) {
  const Eigen::Index p = cache.block_p[block];
  const Eigen::Index q = p + vech_len(p);
  Eigen::MatrixXd dH = Eigen::MatrixXd::Zero(q, q);
  std::int64_t n_block = 0;

  for (const FIMLPattern& pat : cache.patterns) {
    if (pat.block != block) continue;
    n_block += pat.n_obs;
    const auto& obs = pat.observed;
    const Eigen::Index m = static_cast<Eigen::Index>(obs.size());
    const double nr = static_cast<double>(pat.n_obs);

    const Eigen::MatrixXd Sigma_o = select_square(Sigma, obs);
    Eigen::LLT<Eigen::MatrixXd> llt(Sigma_o);
    if (llt.info() != Eigen::Success) {
      return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
          "ML2S Gamma influence: Sigma_oo is not positive definite"));
    }
    Eigen::MatrixXd A = llt.solve(Eigen::MatrixXd::Identity(m, m));
    A = 0.5 * (A + A.transpose()).eval();
    const Eigen::MatrixXd dS_o = select_square(dSigma, obs);
    const Eigen::MatrixXd dA = -(A * dS_o * A);
    const Eigen::VectorXd dmu_o = select_vector(dmu, obs);
    const Eigen::VectorXd Mu_o = select_vector(mu, obs);
    const Eigen::VectorXd dbar = pat.mean - Mu_o;
    const Eigen::VectorXd ddbar = -dmu_o;

    const Eigen::VectorXd Zsum = nr * (A * dbar);
    const Eigen::VectorXd dZsum = nr * (dA * dbar + A * ddbar);
    const Eigen::MatrixXd sum_ddT = nr * (pat.cov + dbar * dbar.transpose());
    const Eigen::MatrixXd dsum_ddT =
        nr * (ddbar * dbar.transpose() + dbar * ddbar.transpose());
    const Eigen::MatrixXd M = A * sum_ddT * A;
    const Eigen::MatrixXd dM =
        dA * sum_ddT * A + A * dsum_ddT * A + A * sum_ddT * dA;

    for (Eigen::Index j = 0; j < m; ++j) {
      const Eigen::Index fj = obs[static_cast<std::size_t>(j)];
      for (Eigen::Index i = 0; i < m; ++i) {
        dH(obs[static_cast<std::size_t>(i)], fj) += 2.0 * nr * dA(i, j);
      }
    }

    std::vector<SigmaBasis> basis;
    basis.reserve(static_cast<std::size_t>(m * (m + 1) / 2));
    for (Eigen::Index cj = 0; cj < m; ++cj) {
      for (Eigen::Index ri = cj; ri < m; ++ri) {
        const Eigen::Index full_r0 = obs[static_cast<std::size_t>(ri)];
        const Eigen::Index full_c = obs[static_cast<std::size_t>(cj)];
        SigmaBasis e;
        e.full_index = p + vech_index(p, std::max(full_r0, full_c),
                                      std::min(full_r0, full_c));
        e.a = ri;
        e.b = cj;
        Eigen::VectorXd dADz;
        if (ri == cj) {
          dADz = dA.col(ri) * Zsum(ri) + A.col(ri) * dZsum(ri);
        } else {
          dADz = dA.col(ri) * Zsum(cj) + A.col(ri) * dZsum(cj) +
                 dA.col(cj) * Zsum(ri) + A.col(cj) * dZsum(ri);
        }
        for (Eigen::Index i = 0; i < m; ++i) {
          const Eigen::Index full_i = obs[static_cast<std::size_t>(i)];
          const double h = 2.0 * dADz(i);
          dH(full_i, e.full_index) += h;
          dH(e.full_index, full_i) += h;
        }
        basis.push_back(e);
      }
    }

    for (std::size_t kk = 0; kk < basis.size(); ++kk) {
      const SigmaBasis& k = basis[kk];
      for (std::size_t ll = 0; ll <= kk; ++ll) {
        const SigmaBasis& l = basis[ll];
        const double h =
            -nr * (basis_trace_xy(dA, A, l, k) + basis_trace_xy(A, dA, l, k)) +
            (basis_trace_xy(dA, M, l, k) + basis_trace_xy(A, dM, l, k)) +
            (basis_trace_xy(dA, M, k, l) + basis_trace_xy(A, dM, k, l));
        dH(k.full_index, l.full_index) += h;
        if (kk != ll) dH(l.full_index, k.full_index) += h;
      }
    }
  }

  if (n_block <= 0) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "ML2S Gamma influence: block has no observations"));
  }
  dH /= static_cast<double>(n_block);
  return Eigen::MatrixXd(0.5 * (dH + dH.transpose()));
}

// Per-block precompute for the analytic Γ-influence: base scores S, total info
// inverse H⁻¹, and the sandwich H⁻¹JH⁻¹ at the (unperturbed) saturated fit.


post_expected<Ml2sGammaInfluencePrep>
prep_ml2s_gamma_influence(const RawData& raw, const FIMLCache& cache,
                          std::size_t block, const Eigen::VectorXd& mu,
                          const Eigen::MatrixXd& Sigma) {
  auto scores_or = fiml_saturated_scores_block(raw, block, mu, Sigma);
  if (!scores_or.has_value()) return std::unexpected(scores_or.error());
  auto Hbar_or = fiml_saturated_hessian_analytic_block(cache, block, mu, Sigma);
  if (!Hbar_or.has_value()) return std::unexpected(Hbar_or.error());

  const double n = static_cast<double>(raw.X[block].rows());
  const Eigen::MatrixXd H = (n / 2.0) * (*Hbar_or);
  const Eigen::MatrixXd J = 0.25 * (scores_or->transpose() * (*scores_or));
  auto Hinv_or = invert_symmetric(
      H, "ML2S Gamma influence: weighted saturated information");
  if (!Hinv_or.has_value()) return std::unexpected(Hinv_or.error());

  Ml2sGammaInfluencePrep prep;
  prep.n = raw.X[block].rows();
  prep.q = scores_or->cols();
  prep.mu = mu;
  prep.Sigma = Sigma;
  prep.scores = std::move(*scores_or);
  prep.Hinv = std::move(*Hinv_or);
  prep.HiJHi = prep.Hinv * J * prep.Hinv;
  prep.HiJHi = 0.5 * (prep.HiJHi + prep.HiJHi.transpose()).eval();
  return prep;
}

// n·dΓ_b/dw_i for case `i` — the analytic drop-in for
// `weighted_two_stage_gamma_influence_fd_block`.
post_expected<Eigen::MatrixXd>
weighted_two_stage_gamma_influence_analytic_block(
    const RawData& raw, const FIMLCache& cache, std::size_t block,
    const Ml2sGammaInfluencePrep& prep, Eigen::Index i) {
  const Eigen::Index p = prep.Sigma.rows();
  const double n = static_cast<double>(prep.n);
  const Eigen::VectorXd s_i = prep.scores.row(i).transpose();
  const Eigen::VectorXd g_i = -0.5 * s_i;
  const Eigen::VectorXd dtheta = prep.Hinv * g_i;  // Δθ_i = H⁻¹ g_i
  Eigen::VectorXd dmu = dtheta.head(p);
  Eigen::MatrixXd dSigma(p, p);
  vech_unpack(dtheta.segment(p, vech_len(p)), p, dSigma);

  auto Ii_or = fiml_saturated_case_info_block(raw, block, i, prep.mu, prep.Sigma);
  if (!Ii_or.has_value()) return std::unexpected(Ii_or.error());
  auto dS_or = fiml_saturated_scores_directional_block(
      raw, block, prep.mu, prep.Sigma, dmu, dSigma);
  if (!dS_or.has_value()) return std::unexpected(dS_or.error());
  auto dHbar_or = fiml_saturated_hessian_directional_block(
      cache, block, prep.mu, prep.Sigma, dmu, dSigma);
  if (!dHbar_or.has_value()) return std::unexpected(dHbar_or.error());

  // J̇_i = g_i g_iᵀ + ¼(dSᵀS + SᵀdS);  Ḣ_i = I_i + (n/2)·∂H̄/∂θ·Δθ_i.
  const Eigen::MatrixXd Jdot =
      g_i * g_i.transpose() +
      0.25 * (dS_or->transpose() * prep.scores +
              prep.scores.transpose() * (*dS_or));
  const Eigen::MatrixXd Hdot = *Ii_or + (n / 2.0) * (*dHbar_or);

  const Eigen::MatrixXd& Hinv = prep.Hinv;
  const Eigen::MatrixXd& HiJHi = prep.HiJHi;
  Eigen::MatrixXd dGamma =
      HiJHi + n * (-(Hinv * Hdot * HiJHi) + (Hinv * Jdot * Hinv) -
                   (HiJHi * Hdot * Hinv));
  dGamma = 0.5 * (dGamma + dGamma.transpose()).eval();
  return Eigen::MatrixXd(n * dGamma);
}

post_expected<Eigen::MatrixXd>
fiml_saturated_hessian_fd_block(const RawData& raw,
                                std::size_t block,
                                const Eigen::VectorXd& mu,
                                const Eigen::MatrixXd& Sigma,
                                double h_step) {
  const Eigen::Index p = mu.size();
  const Eigen::Index pstar = vech_len(p);
  const Eigen::Index q = p + pstar;
  auto grad_at = [&](const Eigen::VectorXd& mu0,
                     const Eigen::MatrixXd& Sigma0)
      -> post_expected<Eigen::VectorXd> {
    Eigen::LLT<Eigen::MatrixXd> llt(0.5 * (Sigma0 + Sigma0.transpose()));
    if (llt.info() != Eigen::Success) {
      return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
          "FIML robust H1: perturbed Sigma is not positive definite"));
    }
    auto S_or = fiml_saturated_scores_block(raw, block, mu0, Sigma0);
    if (!S_or.has_value()) return std::unexpected(S_or.error());
    return Eigen::VectorXd(S_or->colwise().mean().transpose());
  };

  Eigen::MatrixXd H = Eigen::MatrixXd::Zero(q, q);
  for (Eigen::Index k = 0; k < q; ++k) {
    Eigen::VectorXd mup = mu;
    Eigen::VectorXd mum = mu;
    Eigen::MatrixXd Sp = Sigma;
    Eigen::MatrixXd Sm = Sigma;
    if (k < p) {
      mup(k) += h_step;
      mum(k) -= h_step;
    } else {
      const Eigen::Index vk = k - p;
      const Eigen::Index r = vech_row(p, vk);
      const Eigen::Index c = vech_col(p, vk);
      Sp(r, c) += h_step;
      Sm(r, c) -= h_step;
      if (r != c) {
        Sp(c, r) += h_step;
        Sm(c, r) -= h_step;
      }
    }
    auto gp = grad_at(mup, Sp);
    if (!gp.has_value()) return std::unexpected(gp.error());
    auto gm = grad_at(mum, Sm);
    if (!gm.has_value()) return std::unexpected(gm.error());
    H.col(k) = (*gp - *gm) / (2.0 * h_step);
  }
  return Eigen::MatrixXd(0.5 * (H + H.transpose()));
}

// Gradient of the FIML deviance F with respect to the FULL per-block moments,
// aggregated over observed-value patterns: ∂F/∂Σ_b = G_b in the symmetric
// matrix-derivative sense (dF = tr(G_b · dΣ_b) + u_bᵀ dμ_b), with the
// per-pattern weight Σ_oo⁻¹ − Σ_oo⁻¹(S_r + ddᵀ)Σ_oo⁻¹ scattered into the full
// p×p index space. These are the weights the second-order chain-rule term of
// the observed Hessian contracts against ∂²Σ/∂θ_a∂θ_b and ∂²μ/∂θ_a∂θ_b.


post_expected<FIMLMomentGradient>
fiml_moment_gradient(const FIMLCache& cache,
                     const model::ImpliedMoments& moments) {
  FIMLMomentGradient out;
  const std::size_t n_blocks = cache.block_p.size();
  out.G.resize(n_blocks);
  out.u.resize(n_blocks);
  for (std::size_t b = 0; b < n_blocks; ++b) {
    const Eigen::Index p = cache.block_p[b];
    out.G[b] = Eigen::MatrixXd::Zero(p, p);
    out.u[b] = Eigen::VectorXd::Zero(p);
  }

  for (const FIMLPattern& pat : cache.patterns) {
    const auto& obs = pat.observed;
    const Eigen::Index q = static_cast<Eigen::Index>(obs.size());
    const Eigen::MatrixXd Sigma_o = select_square(moments.sigma[pat.block], obs);
    const Eigen::VectorXd Mu_o = select_vector(moments.mu[pat.block], obs);
    const Eigen::VectorXd d = pat.mean - Mu_o;
    const Eigen::MatrixXd A = pat.cov + d * d.transpose();

    Eigen::LLT<Eigen::MatrixXd> llt(Sigma_o);
    if (llt.info() != Eigen::Success) {
      return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
          "FIML observed Hessian: implied observed-pattern Σ is not "
          "positive definite"));
    }
    const Eigen::MatrixXd SigmaInv =
        llt.solve(Eigen::MatrixXd::Identity(q, q));
    Eigen::MatrixXd Gp = SigmaInv - SigmaInv * A * SigmaInv;
    Gp = 0.5 * (Gp + Gp.transpose()).eval();
    const Eigen::VectorXd z = SigmaInv * d;

    const double scale = static_cast<double>(pat.n_obs) /
                         static_cast<double>(cache.n_total);
    auto& Gb = out.G[pat.block];
    auto& ub = out.u[pat.block];
    for (Eigen::Index cj = 0; cj < q; ++cj) {
      const Eigen::Index c = obs[static_cast<std::size_t>(cj)];
      for (Eigen::Index ri = 0; ri < q; ++ri) {
        const Eigen::Index r = obs[static_cast<std::size_t>(ri)];
        Gb(r, c) += scale * Gp(ri, cj);
      }
      ub(c) += -2.0 * scale * z(cj);
    }
  }
  return out;
}

// Analytic observed Hessian of the per-observation-averaged FIML deviance F
// with respect to θ — same object as `fiml_observed_hessian_fd`, exact instead
// of central-difference. Chain rule through the moment map (μ(θ), Σ(θ)):
//
//   H = Σ_b (n_b/N) · Δ_bᵀ · W_b · Δ_b                       (first order)
//     + Σ_b [ tr(G_b · ∂²Σ_b/∂θ_a∂θ_b) + u_bᵀ ∂²μ_b/∂θ_a∂θ_b ]  (second order)
//
// where W_b is the per-block moment-space Hessian of the mean deviance
// (`fiml_saturated_hessian_analytic_block` evaluated at the model-implied
// moments), Δ_b stacks [∂μ_b/∂θ ; ∂vech(Σ_b)/∂θ], and (G_b, u_b) is the
// pattern-aggregated moment gradient above contracted with the closed-form
// LISREL second derivatives (`detail::second_sigma_trace` / `detail::second_mu`).
post_expected<Eigen::MatrixXd>
fiml_observed_hessian_analytic(spec::LatentStructure pt,
                               const model::MatrixRep& rep,
                               const FIMLCache& cache,
                               const SampleStats& start_samp,
                               const Estimates& est) {
  if (auto e = resolve_fixed_x_from_sample(pt, rep, start_samp); !e.has_value()) {
    return std::unexpected(fit_to_post(e.error(), "resolve_fixed_x_from_sample"));
  }
  auto ev_or = model::ModelEvaluator::build(pt, rep);
  if (!ev_or.has_value()) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "ModelEvaluator::build failed: " + ev_or.error().detail));
  }
  const auto& ev = *ev_or;
  const Eigen::Index q = static_cast<Eigen::Index>(ev.n_free());
  if (est.theta.size() != q) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "FIML observed Hessian: theta size mismatch"));
  }

  auto am_or = ev.assembled(est.theta);
  if (!am_or.has_value()) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "ModelEvaluator::assembled failed: " + am_or.error().detail));
  }
  auto eval_or = ev.evaluate(est.theta, true, true);
  if (!eval_or.has_value()) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "ModelEvaluator::evaluate failed: " + eval_or.error().detail));
  }
  const auto& eval = *eval_or;
  const auto locs = ev.param_locations();

  const std::size_t n_blocks = cache.block_p.size();
  Eigen::Index total_p = 0;
  for (std::size_t b = 0; b < n_blocks; ++b) total_p += cache.block_p[b];
  if (eval.J_mu.rows() != total_p || eval.J_mu.cols() != q) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "FIML observed Hessian: mean structure is required"));
  }

  std::vector<std::int64_t> n_block(n_blocks, 0);
  for (const FIMLPattern& pat : cache.patterns) n_block[pat.block] += pat.n_obs;

  Eigen::MatrixXd H = Eigen::MatrixXd::Zero(q, q);

  // First-order term: per-block moment-space Hessian at the implied moments,
  // contracted with the stacked [μ; vech Σ] Jacobian.
  for (std::size_t b = 0; b < n_blocks; ++b) {
    const Eigen::Index p = cache.block_p[b];
    const Eigen::Index pstar = vech_len(p);
    auto W_or = fiml_saturated_hessian_analytic_block(cache, b,
                                                      eval.moments.mu[b],
                                                      eval.moments.sigma[b]);
    if (!W_or.has_value()) return std::unexpected(W_or.error());

    Eigen::MatrixXd Delta(p + pstar, q);
    Delta.topRows(p) = eval.J_mu.middleRows(cache.mu_offsets[b], p);
    Delta.bottomRows(pstar) =
        eval.J_sigma.middleRows(cache.sigma_offsets[b], pstar);

    const double weight = static_cast<double>(n_block[b]) /
                          static_cast<double>(cache.n_total);
    H.noalias() += weight * (Delta.transpose() * ((*W_or) * Delta));
  }

  // Second-order term: pattern-aggregated moment gradient contracted with the
  // closed-form LISREL second derivatives.
  auto mg_or = fiml_moment_gradient(cache, eval.moments);
  if (!mg_or.has_value()) return std::unexpected(mg_or.error());
  const FIMLMomentGradient& mg = *mg_or;

  std::vector<detail::SecondOrderWeights> sow;
  sow.reserve(n_blocks);
  for (std::size_t b = 0; b < n_blocks; ++b) {
    sow.push_back(detail::SecondOrderWeights::build(mg.G[b],
                                                    am_or->blocks[b],
                                                    /*has_means=*/true));
  }

  for (Eigen::Index a = 0; a < q; ++a) {
    for (Eigen::Index b = a; b < q; ++b) {
      const auto& la = locs[static_cast<std::size_t>(a)];
      const auto& lb = locs[static_cast<std::size_t>(b)];
      if (la.block != lb.block) continue;
      const auto blk = static_cast<std::size_t>(la.block);
      const auto& bm = am_or->blocks[blk];
      double h2 = detail::second_sigma_trace(la, lb, sow[blk], bm);
      h2 += detail::second_mu(la, lb, bm, sow[blk].A_alpha).dot(mg.u[blk]);
      H(a, b) += h2;
      if (a != b) H(b, a) += h2;
    }
  }

  return Eigen::MatrixXd(0.5 * (H + H.transpose()));
}

post_expected<double>
fiml_saturated_trace_h1(const RawData& raw,
                        const FIMLCache& cache,
                        const FIMLH1& h1) {
  if (cache.block_p.size() != raw.X.size()) {
    return std::unexpected(make_post_err(PostError::Kind::NumericIssue,
        "FIML robust H1: cache and raw block count mismatch"));
  }
  if (auto e = validate_h1_blocks(cache, h1); !e.has_value()) {
    return std::unexpected(fit_to_post(e.error(), "FIML H1 moments"));
  }

  double trace = 0.0;
  for (std::size_t b = 0; b < raw.X.size(); ++b) {
    const Eigen::VectorXd& h1_mu = h1.mu[b];
    const Eigen::MatrixXd& h1_sigma = h1.sigma[b];
    auto h1_scores_or = fiml_saturated_scores_block(raw, b,
                                                    h1_mu, h1_sigma);
    if (!h1_scores_or.has_value()) return std::unexpected(h1_scores_or.error());
    auto h1_H_or = fiml_saturated_hessian_analytic_block(cache, b, h1_mu,
                                                         h1_sigma);
    if (!h1_H_or.has_value()) return std::unexpected(h1_H_or.error());

    const double n_block = static_cast<double>(raw.X[b].rows());
    const Eigen::MatrixXd h1_meat =
        (h1_scores_or->transpose() * (*h1_scores_or)) / n_block;
    auto h1_Hinv_or = invert_symmetric(*h1_H_or,
                                       "fiml_robust_mlr: H1 observed Hessian");
    if (!h1_Hinv_or.has_value()) return std::unexpected(h1_Hinv_or.error());
    trace += 0.5 * ((*h1_Hinv_or) * h1_meat).trace();
  }
  return trace;
}


}  // namespace internal

}  // namespace magmaan::estimate::fiml
