// @generated by r-package/tools/vendor-cpp.sh from cpp/src/estimate/ml_psd_fallback.cpp — DO NOT EDIT; re-run `just vendor`.
#include "magmaan/estimate/frontier/ml_psd_fallback.hpp"

#include <cmath>
#include <utility>

namespace magmaan::estimate::frontier {
namespace {

bool accepted(const fit_expected<Estimates>& fit) {
  return fit.has_value() && fit_verdict(*fit).status == FitCheck::Passed &&
      fit->diagnostics.admissibility.admissible;
}

bool usable_start(const Estimates& fit, Eigen::Index n) {
  // Candidate retention must not silently add a warm-start policy for the
  // soft exits that previously returned errors. Keep their original x0 path.
  if (!fit.audit.stationary &&
      (fit.optimizer_status == optim::OptimStatus::BudgetExhausted ||
       fit.optimizer_status == optim::OptimStatus::LineSearchFailed)) return false;
  return fit.theta.size() == n && fit.theta.allFinite() &&
      std::isfinite(fit.fmin) && fit.diagnostics.sigma_pd_all &&
      fit.diagnostics.lin_eq_satisfied && fit.diagnostics.nl_eq_satisfied;
}

}  // namespace

const Estimates* MlPsdFallbackResult::accepted_fit() const {
  if (psd.has_value()) return accepted(*psd) ? &**psd : nullptr;
  return accepted(ordinary) ? &*ordinary : nullptr;
}

MlPsdFallbackResult fit_ml_psd_fallback(
    spec::LatentStructure pt, const model::MatrixRep& rep,
    const SampleStats& samp, const Eigen::VectorXd& x0,
    MlPsdFallbackOptions options) {
  MlPsdFallbackResult out{
      fit_ml(pt, rep, samp, x0, {}, options.ordinary_backend, options.ordinary),
      std::nullopt};
  if (accepted(out.ordinary)) return out;

  if (!out.ordinary.has_value()) {
    out.reason = PsdFallbackReason::OrdinaryError;
  } else if (fit_verdict(*out.ordinary).status != FitCheck::Passed) {
    out.reason = PsdFallbackReason::OrdinaryRejected;
  } else {
    out.reason = PsdFallbackReason::OrdinaryInadmissible;
  }
  out.warm_start_used = out.ordinary.has_value() &&
      usable_start(*out.ordinary, x0.size());
  const Eigen::VectorXd& start = out.warm_start_used ? out.ordinary->theta : x0;
  out.psd = fit_ml_psd(std::move(pt), rep, samp, start, options.psd_backend,
                       options.psd, options.covariance);
  return out;
}

}  // namespace magmaan::estimate::frontier
