// @generated by dev/vendor-cpp.sh from src/detail_distribution_math.hpp — DO NOT EDIT; re-run `just vendor`.
#pragma once

#include <algorithm>
#include <cmath>
#include <limits>

namespace magmaan::detail {

inline double nan() noexcept {
  return std::numeric_limits<double>::quiet_NaN();
}

inline double clamp01(double x) noexcept {
  if (std::isnan(x)) return x;
  return std::clamp(x, 0.0, 1.0);
}

inline double gamma_p_series(double a, double x) noexcept {
  if (!(a > 0.0) || x < 0.0) return nan();
  if (x == 0.0) return 0.0;
  double sum = 1.0 / a;
  double term = sum;
  constexpr int max_iter = 200;
  for (int n = 1; n < max_iter; ++n) {
    term *= x / (a + static_cast<double>(n));
    sum += term;
    if (std::abs(term) < std::abs(sum) * 1e-15) break;
  }
  return sum * std::exp(-x + a * std::log(x) - std::lgamma(a));
}

inline double gamma_q_cfrac(double a, double x) noexcept {
  if (!(a > 0.0) || x < 0.0) return nan();
  if (x == 0.0) return 1.0;
  constexpr double fpmin = 1e-300;
  double b = x + 1.0 - a;
  double c = 1.0 / fpmin;
  double d = 1.0 / b;
  double h = d;
  constexpr int max_iter = 200;
  for (int n = 1; n < max_iter; ++n) {
    const double an = -static_cast<double>(n) * (static_cast<double>(n) - a);
    b += 2.0;
    d = an * d + b;
    if (std::abs(d) < fpmin) d = fpmin;
    c = b + an / c;
    if (std::abs(c) < fpmin) c = fpmin;
    d = 1.0 / d;
    const double del = d * c;
    h *= del;
    if (std::abs(del - 1.0) < 1e-15) break;
  }
  return h * std::exp(-x + a * std::log(x) - std::lgamma(a));
}

inline double gamma_p(double a, double x) noexcept {
  if (x < a + 1.0) return gamma_p_series(a, x);
  return 1.0 - gamma_q_cfrac(a, x);
}

inline double gamma_q(double a, double x) noexcept {
  if (x < a + 1.0) return 1.0 - gamma_p_series(a, x);
  return gamma_q_cfrac(a, x);
}

inline double beta_cont_frac(double a, double b, double x) noexcept {
  constexpr int max_iter = 200;
  constexpr double eps = 3e-14;
  constexpr double fpmin = 1e-300;

  const double qab = a + b;
  const double qap = a + 1.0;
  const double qam = a - 1.0;
  double c = 1.0;
  double d = 1.0 - qab * x / qap;
  if (std::abs(d) < fpmin) d = fpmin;
  d = 1.0 / d;
  double h = d;

  for (int m = 1; m <= max_iter; ++m) {
    const double m2 = 2.0 * static_cast<double>(m);
    double aa = static_cast<double>(m) * (b - static_cast<double>(m)) * x /
                ((qam + m2) * (a + m2));
    d = 1.0 + aa * d;
    if (std::abs(d) < fpmin) d = fpmin;
    c = 1.0 + aa / c;
    if (std::abs(c) < fpmin) c = fpmin;
    d = 1.0 / d;
    h *= d * c;

    aa = -(a + static_cast<double>(m)) * (qab + static_cast<double>(m)) * x /
         ((a + m2) * (qap + m2));
    d = 1.0 + aa * d;
    if (std::abs(d) < fpmin) d = fpmin;
    c = 1.0 + aa / c;
    if (std::abs(c) < fpmin) c = fpmin;
    d = 1.0 / d;
    const double del = d * c;
    h *= del;
    if (std::abs(del - 1.0) < eps) break;
  }
  return h;
}

inline double regularized_beta(double a, double b, double x) noexcept {
  if (!(a > 0.0) || !(b > 0.0) || x < 0.0 || x > 1.0) return nan();
  if (x == 0.0) return 0.0;
  if (x == 1.0) return 1.0;
  const double bt = std::exp(std::lgamma(a + b) - std::lgamma(a) -
                             std::lgamma(b) + a * std::log(x) +
                             b * std::log1p(-x));
  if (x < (a + 1.0) / (a + b + 2.0)) {
    return bt * beta_cont_frac(a, b, x) / a;
  }
  return 1.0 - bt * beta_cont_frac(b, a, 1.0 - x) / b;
}

inline double inverse_regularized_beta(double p,
                                       double a,
                                       double b) noexcept {
  if (!(a > 0.0) || !(b > 0.0) || p < 0.0 || p > 1.0) return nan();
  if (p == 0.0) return 0.0;
  if (p == 1.0) return 1.0;
  double lo = 0.0;
  double hi = 1.0;
  double mid = 0.5;
  for (int iter = 0; iter < 120; ++iter) {
    mid = 0.5 * (lo + hi);
    const double cdf = regularized_beta(a, b, mid);
    if (!std::isfinite(cdf)) return nan();
    if (cdf < p) lo = mid;
    else hi = mid;
  }
  return mid;
}

inline double inverse_gamma_p(double p,
                              double shape,
                              double scale) noexcept {
  if (!(shape > 0.0) || !(scale > 0.0) || p < 0.0 || p > 1.0) return nan();
  if (p == 0.0) return 0.0;
  if (p == 1.0) return std::numeric_limits<double>::infinity();
  double lo = 0.0;
  double hi = std::max(1.0, shape * scale);
  while (gamma_p(shape, hi / scale) < p) {
    hi *= 2.0;
    if (!std::isfinite(hi)) return hi;
  }
  double mid = hi;
  for (int iter = 0; iter < 140; ++iter) {
    mid = 0.5 * (lo + hi);
    const double cdf = gamma_p(shape, mid / scale);
    if (!std::isfinite(cdf)) return nan();
    if (cdf < p) lo = mid;
    else hi = mid;
  }
  return mid;
}

inline double student_t_cdf(double x, double df) noexcept {
  if (!(df > 0.0)) return nan();
  if (x == 0.0) return 0.5;
  const double z = df / (df + x * x);
  const double ib = regularized_beta(0.5 * df, 0.5, z);
  if (!std::isfinite(ib)) return nan();
  return x > 0.0 ? 1.0 - 0.5 * ib : 0.5 * ib;
}

inline double student_t_quantile(double p, double df) noexcept {
  if (!(df > 0.0) || p < 0.0 || p > 1.0) return nan();
  if (p == 0.0) return -std::numeric_limits<double>::infinity();
  if (p == 1.0) return std::numeric_limits<double>::infinity();
  if (p == 0.5) return 0.0;
  const bool neg = p < 0.5;
  const double target = neg ? 1.0 - p : p;
  double lo = 0.0;
  double hi = 1.0;
  while (student_t_cdf(hi, df) < target) {
    hi *= 2.0;
    if (!std::isfinite(hi)) return neg ? -hi : hi;
  }
  double mid = hi;
  for (int iter = 0; iter < 140; ++iter) {
    mid = 0.5 * (lo + hi);
    if (student_t_cdf(mid, df) < target) lo = mid;
    else hi = mid;
  }
  return neg ? -mid : mid;
}

inline double f_upper_tail(double x, double d1, double d2) noexcept {
  if (!(x >= 0.0) || !(d1 > 0.0) || !(d2 > 0.0)) return nan();
  if (x == 0.0) return 1.0;
  const bool d1_inf = std::isinf(d1);
  const bool d2_inf = std::isinf(d2);
  if (d1_inf && d2_inf) {
    if (x < 1.0) return 1.0;
    if (x > 1.0) return 0.0;
    return 0.5;
  }
  if (d1_inf) {
    return clamp01(gamma_p(0.5 * d2, 0.5 * d2 / x));
  }
  if (d2_inf) {
    return clamp01(gamma_q(0.5 * d1, 0.5 * d1 * x));
  }
  const double z = d2 / (d2 + d1 * x);
  return clamp01(regularized_beta(0.5 * d2, 0.5 * d1, z));
}

}  // namespace magmaan::detail
