// Detective harness for magmaan's ML convergence failures.
//
// The benchmark smoke found ML fails on bollen_democracy_sem (LineSearchFailed
// after 0 iters) and bfi_5factor (max_iter reached). This file probes the
// objective, gradient, start values, optimizer, and conditioning at the points
// that matter, and prints a staged report. It is diagnostic, not a pass/fail
// gate -- the CHECKs guard only the conclusions that hold once understood.
//
// Fixtures: the shared lavaan-parity fixtures
// tests/fixtures/parity/<case>/reference.json, generated by
// tools/regen_parity_fixtures.R (sample cov, n_obs, model, and lavaan's
// theta-hat + start values in magmaan's free-parameter order). The pass/fail
// regression gate lives in tests/golden/lavaan_parity_golden_test.cpp; this
// file keeps the staged diagnostic report.
//
// Run it directly for the full report:
//   ./build/dev/tests/magmaan_test_estimate -tc="convergence diagnostics*" -s

#include <doctest/doctest.h>

#include <cmath>
#include <cstdio>
#include <fstream>
#include <limits>
#include <sstream>
#include <string>
#include <vector>

#include <Eigen/Cholesky>
#include <Eigen/Core>
#include <Eigen/Eigenvalues>

#include <nlohmann/json.hpp>

#include "magmaan/data/sample_stats.hpp"
#include "magmaan/error.hpp"
#include "magmaan/estimate/fit.hpp"
#include "magmaan/estimate/start_values.hpp"
#include "magmaan/model/matrix_rep.hpp"
#include "magmaan/model/model_evaluator.hpp"
#include "magmaan/nt/ml.hpp"
#include "magmaan/optim/lbfgs_optimizer.hpp"
#include "magmaan/parse/parser.hpp"
#include "magmaan/spec/lavaanify.hpp"
#include "magmaan/spec/start_hints.hpp"

#ifdef MAGMAAN_WITH_CERES
#include "magmaan/optim/ceres_optimizer.hpp"
#endif

using magmaan::FitError;
using magmaan::data::SampleStats;
using magmaan::estimate::simple_start_values;
using magmaan::model::MatId;
using magmaan::model::ModelEvaluator;
using magmaan::model::build_matrix_rep;
using magmaan::parse::Parser;
using magmaan::spec::lavaanify;

namespace {

// ---- fixture -------------------------------------------------------------
struct Fixture {
  std::string case_id;
  std::string model;
  int n_obs = 0;
  int n_free = 0;
  Eigen::MatrixXd S;            // sample covariance
  Eigen::VectorXd theta_hat;    // lavaan optimum, magmaan free order
  Eigen::VectorXd theta_start;  // lavaan start values, magmaan free order
  double lavaan_fmin = 0.0;     // lavaan reports F/2; magmaan F == 2 * this
};

Fixture load_fixture(const std::string& name) {
  const std::string path = std::string(MAGMAAN_FIXTURES_DIR) + "/parity/" +
                            name + "/reference.json";
  std::ifstream in(path);
  REQUIRE_MESSAGE(in.is_open(), "missing fixture: ", path);
  std::stringstream ss;
  ss << in.rdbuf();
  auto j = nlohmann::json::parse(ss.str(), nullptr, false);
  REQUIRE_FALSE(j.is_discarded());

  Fixture f;
  f.case_id = j["case_id"].get<std::string>();
  f.model = j["model"].get<std::string>();
  f.n_obs = j["n_obs"].get<int>();
  f.n_free = j["n_free"].get<int>();
  f.lavaan_fmin = j["lavaan_fmin"].get<double>();

  const auto& vals = j["sample_cov"]["values"];
  const auto p = static_cast<Eigen::Index>(vals.size());
  f.S.resize(p, p);
  for (Eigen::Index r = 0; r < p; ++r)
    for (Eigen::Index c = 0; c < p; ++c)
      f.S(r, c) = vals[static_cast<std::size_t>(r)][static_cast<std::size_t>(c)]
                      .get<double>();

  const auto rd = [](const nlohmann::json& arr) {
    Eigen::VectorXd v(static_cast<Eigen::Index>(arr.size()));
    for (Eigen::Index k = 0; k < v.size(); ++k)
      v(k) = arr[static_cast<std::size_t>(k)].get<double>();
    return v;
  };
  f.theta_hat = rd(j["theta_hat"]);
  f.theta_start = rd(j["theta_start_lavaan"]);
  return f;
}

// ---- a built, ready-to-probe case ---------------------------------------
struct Case {
  magmaan::spec::LatentStructure pt;
  magmaan::model::MatrixRep mr;
  SampleStats samp;
};

Case build_case(const Fixture& f) {
  auto fp = Parser::parse(f.model);
  REQUIRE(fp.has_value());
  magmaan::spec::LavaanifyOptions opts;
  opts.auto_cov_y = true;  // mirrors lavaan cfa/sem and the benchmark runner
  auto pt = lavaanify(*fp, opts);
  REQUIRE(pt.has_value());
  auto mr = build_matrix_rep(*pt);
  REQUIRE(mr.has_value());

  Case c;
  c.pt = std::move(*pt);
  c.mr = std::move(*mr);
  c.samp.S.push_back(f.S);
  c.samp.n_obs.push_back(f.n_obs);
  return c;
}

const char* mat_name(MatId m) {
  switch (m) {
    case MatId::Lambda: return "Lambda";
    case MatId::Theta:  return "Theta";
    case MatId::Psi:    return "Psi";
    case MatId::Beta:   return "Beta";
    case MatId::Nu:     return "Nu";
    case MatId::Alpha:  return "Alpha";
  }
  return "?";
}

const char* err_kind(FitError::Kind k) {
  switch (k) {
    case FitError::Kind::OptimizerNonConvergence:  return "OptimizerNonConvergence";
    case FitError::Kind::NonFiniteObjective:       return "NonFiniteObjective";
    case FitError::Kind::NonPositiveDefiniteSigma: return "NonPositiveDefiniteSigma";
    case FitError::Kind::NonPositiveDefiniteSample:return "NonPositiveDefiniteSample";
    case FitError::Kind::LineSearchFailed:         return "LineSearchFailed";
    case FitError::Kind::InvalidStartValues:       return "InvalidStartValues";
    case FitError::Kind::NumericIssue:             return "NumericIssue";
  }
  return "?";
}

// Objective F(theta); returns +inf when the implied Sigma is non-PD.
double objective(ModelEvaluator& ev, const SampleStats& samp,
                 const Eigen::VectorXd& theta) {
  auto sm = ev.sigma(theta);
  if (!sm.has_value()) return std::numeric_limits<double>::infinity();
  auto f = magmaan::nt::ml_value(samp, *sm);
  return f.has_value() ? *f : std::numeric_limits<double>::infinity();
}

// Analytic gradient; empty on failure.
Eigen::VectorXd grad_analytic(ModelEvaluator& ev, const SampleStats& samp,
                              const Eigen::VectorXd& theta) {
  auto sm = ev.sigma(theta);
  auto J = ev.dsigma_dtheta(theta);
  if (!sm.has_value() || !J.has_value()) return {};
  auto g = magmaan::nt::ml_gradient(samp, *sm, *J);
  return g.has_value() ? *g : Eigen::VectorXd{};
}

// Central-difference gradient.
Eigen::VectorXd grad_fd(ModelEvaluator& ev, const SampleStats& samp,
                        const Eigen::VectorXd& theta, double h = 1e-6) {
  Eigen::VectorXd g(theta.size());
  for (Eigen::Index k = 0; k < theta.size(); ++k) {
    Eigen::VectorXd tp = theta, tm = theta;
    tp(k) += h;
    tm(k) -= h;
    g(k) = (objective(ev, samp, tp) - objective(ev, samp, tm)) / (2.0 * h);
  }
  return g;
}

double min_eig(const Eigen::MatrixXd& M) {
  Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> es(M, Eigen::EigenvaluesOnly);
  return es.eigenvalues()(0);
}

magmaan::spec::Starts hint_start(const Eigen::VectorXd& v) {
  magmaan::spec::Starts s;
  s.hint.assign(v.data(), v.data() + v.size());
  return s;
}

// Fit with a given optimizer + start, print outcome and distance to theta-hat.
void report_fit(const char* tag, const magmaan::spec::LatentStructure& pt,
                const magmaan::model::MatrixRep& mr, const SampleStats& samp,
                magmaan::optim::LbfgsOptions opts, const magmaan::spec::Starts& s,
                const Eigen::VectorXd& theta_hat) {
  auto x0_or = simple_start_values(pt, mr, samp, s);
  if (!x0_or.has_value()) {
    std::printf("       %-28s FAIL  start-value computation\n", tag);
    return;
  }
  auto est = magmaan::estimate::fit_ml(pt, mr, samp, *x0_or, {},
                                       magmaan::estimate::Backend::Lbfgs, opts);
  if (est.has_value()) {
    const double dist = (est->theta - theta_hat).cwiseAbs().maxCoeff();
    std::printf("       %-28s OK    fmin=%.6f iters=%-4d max|theta-hat|=%.2e\n",
                tag, est->fmin, est->iterations, dist);
  } else {
    std::printf("       %-28s FAIL  %-24s f=%.6f iters=%d\n", tag,
                err_kind(est.error().kind), est.error().f_value,
                est.error().iterations);
  }
}

// -------------------------------------------------------------------------
void run_diagnostics(const std::string& name) {
  const Fixture f = load_fixture(name);
  Case c = build_case(f);
  auto ev_or = ModelEvaluator::build(c.pt, c.mr);
  REQUIRE(ev_or.has_value());
  ModelEvaluator ev = std::move(*ev_or);

  std::printf("\n================ convergence diagnostics: %s ================\n",
              f.case_id.c_str());
  std::printf("n_obs=%d  n_free(lavaan)=%d  n_free(magmaan)=%lld  "
              "lavaan F=%.6f (fmin=%.6f)\n",
              f.n_obs, f.n_free, static_cast<long long>(ev.n_free()),
              2.0 * f.lavaan_fmin, f.lavaan_fmin);
  REQUIRE(static_cast<Eigen::Index>(ev.n_free()) == f.theta_hat.size());

  // ---- Phase 0: wiring self-check --------------------------------------
  const double F_hat = objective(ev, c.samp, f.theta_hat);
  std::printf("[P0] F(lavaan theta-hat) = %.6f   expected ~ %.6f   %s\n",
              F_hat, 2.0 * f.lavaan_fmin,
              std::abs(F_hat - 2.0 * f.lavaan_fmin) < 1e-3 ? "OK" : "MISMATCH");
  CHECK_MESSAGE(std::abs(F_hat - 2.0 * f.lavaan_fmin) < 1e-3,
                "fixture wiring: magmaan F at lavaan theta-hat must equal "
                "2 * lavaan fmin");

  // ---- magmaan's own start values --------------------------------------
  auto x0_or = simple_start_values(c.pt, c.mr, c.samp, {});
  REQUIRE(x0_or.has_value());
  const Eigen::VectorXd x0 = *x0_or;
  const double F0 = objective(ev, c.samp, x0);
  std::printf("[P0] F(magmaan simple_start_values) = %.6f\n", F0);

  // ---- Phase 1: gradient correctness -----------------------------------
  std::printf("[P1] analytic-vs-FD gradient, max|d| by parameter class:\n");
  const auto locs = ev.param_locations();
  struct Pt { const char* tag; Eigen::VectorXd theta; };
  for (const Pt& p : {Pt{"simple_start", x0}, Pt{"lavaan_theta_hat", f.theta_hat}}) {
    const Eigen::VectorXd ga = grad_analytic(ev, c.samp, p.theta);
    const Eigen::VectorXd gf = grad_fd(ev, c.samp, p.theta);
    if (ga.size() != gf.size() || ga.size() == 0) {
      std::printf("       %-18s gradient unavailable (non-PD Sigma)\n", p.tag);
      continue;
    }
    double worst = 0.0;
    std::string worst_cls;
    // per-class maxima
    const char* classes[] = {"Lambda", "Theta-diag", "Theta-offdiag",
                             "Psi-diag", "Psi-offdiag", "Beta", "Nu", "Alpha"};
    double cls_max[8] = {0};
    for (Eigen::Index k = 0; k < ga.size(); ++k) {
      const auto& l = locs[static_cast<std::size_t>(k)];
      int ci = 7;
      switch (l.mat) {
        case MatId::Lambda: ci = 0; break;
        case MatId::Theta:  ci = (l.row == l.col) ? 1 : 2; break;
        case MatId::Psi:    ci = (l.row == l.col) ? 3 : 4; break;
        case MatId::Beta:   ci = 5; break;
        case MatId::Nu:     ci = 6; break;
        case MatId::Alpha:  ci = 7; break;
      }
      const double d = std::abs(ga(k) - gf(k));
      if (d > cls_max[ci]) cls_max[ci] = d;
      if (d > worst) { worst = d; worst_cls = mat_name(l.mat); }
    }
    std::printf("       %-18s overall max|d|=%.3e  (worst class: %s)\n",
                p.tag, worst, worst_cls.c_str());
    for (int i = 0; i < 8; ++i)
      if (cls_max[i] > 0.0)
        std::printf("         %-16s %.3e\n", classes[i], cls_max[i]);
  }

  // ---- Phase 2: objective landscape along the descent ray --------------
  std::printf("[P2] F along the steepest-descent ray from simple_start:\n");
  const Eigen::VectorXd g0 = grad_analytic(ev, c.samp, x0);
  if (g0.size() == x0.size()) {
    std::printf("       ||grad(start)|| = %.4e\n", g0.norm());
    auto sm0 = ev.sigma(x0);
    if (sm0.has_value())
      std::printf("       min eig Sigma(start) = %.4e\n", min_eig(sm0->sigma[0]));
    bool any_decrease = false;
    for (double t : {1e-8, 1e-6, 1e-4, 1e-3, 1e-2, 1e-1, 0.5, 1.0}) {
      const double Ft = objective(ev, c.samp, (x0 - t * g0).eval());
      std::printf("       t=%-9.0e F=%s%s\n", t,
                  std::isfinite(Ft) ? std::to_string(Ft).c_str() : "+inf",
                  (std::isfinite(Ft) && Ft < F0) ? "  <-- decreases" : "");
      if (std::isfinite(Ft) && Ft < F0) any_decrease = true;
    }
    std::printf("       => %s along -grad\n",
                any_decrease ? "a decreasing step EXISTS"
                             : "NO decreasing step (descent dir exits PD region)");
  } else {
    std::printf("       gradient unavailable at start\n");
  }

  // ---- Phase 3: start-value sensitivity --------------------------------
  std::printf("[P3] estimate::fit from different starts (default LBFGS):\n");
  const magmaan::optim::LbfgsOptions lbfgs_default{};
  report_fit("magmaan heuristic", c.pt, c.mr, c.samp, lbfgs_default,
             magmaan::spec::Starts{}, f.theta_hat);
  report_fit("lavaan theta-hat", c.pt, c.mr, c.samp, lbfgs_default,
             hint_start(f.theta_hat), f.theta_hat);
  report_fit("lavaan start values", c.pt, c.mr, c.samp, lbfgs_default,
             hint_start(f.theta_start), f.theta_hat);

  // Regression guard: the default heuristic start must reach lavaan's optimum.
  // This is the bug the investigation fixed -- if it regresses, this fails.
  {
    auto est = magmaan::estimate::fit_ml(c.pt, c.mr, c.samp, x0, {},
                                         magmaan::estimate::Backend::Lbfgs,
                                         lbfgs_default);
    CHECK_MESSAGE(est.has_value(),
                  "ML must converge from the default heuristic start");
    if (est.has_value()) {
      CHECK(std::abs(est->fmin - 2.0 * f.lavaan_fmin) < 1e-3);
      CHECK((est->theta - f.theta_hat).cwiseAbs().maxCoeff() < 1e-3);
    }
  }

  // ---- Phase 4: optimizer / line-search comparison ---------------------
  std::printf("[P4] LBFGS gtol sweep (heuristic start | lavaan theta-hat):\n");
  for (double gt : {1e-7, 1e-5, 1e-3, 1e-1}) {
    magmaan::optim::LbfgsOptions o;
    o.gtol = gt;
    char t1[48], t2[48];
    std::snprintf(t1, sizeof t1, "gtol=%.0e heuristic", gt);
    std::snprintf(t2, sizeof t2, "gtol=%.0e lavaan-hat", gt);
    report_fit(t1, c.pt, c.mr, c.samp, o,
               magmaan::spec::Starts{}, f.theta_hat);
    report_fit(t2, c.pt, c.mr, c.samp, o,
               hint_start(f.theta_hat), f.theta_hat);
  }
  {
    magmaan::optim::LbfgsOptions o;
    o.max_iter = 20000;
    report_fit("max_iter=20000 heuristic", c.pt, c.mr, c.samp,
               o, magmaan::spec::Starts{},
               f.theta_hat);
  }
#ifdef MAGMAAN_WITH_CERES
  std::printf("[P4] Ceres trust-region:\n");
  report_fit("ceres / heuristic", c.pt, c.mr, c.samp,
             magmaan::optim::LbfgsOptions{}, magmaan::spec::Starts{},
             f.theta_hat);
  report_fit("ceres / lavaan theta-hat", c.pt, c.mr, c.samp,
             magmaan::optim::LbfgsOptions{}, hint_start(f.theta_hat),
             f.theta_hat);
#else
  std::printf("[P4] Ceres backend not built (configure with the `ceres` preset)\n");
#endif

  // ---- Phase 5: conditioning at theta-hat ------------------------------
  std::printf("[P5] FD Hessian conditioning at lavaan theta-hat:\n");
  {
    const Eigen::Index n = f.theta_hat.size();
    Eigen::MatrixXd H(n, n);
    const double h = 1e-5;
    bool ok = true;
    for (Eigen::Index k = 0; k < n && ok; ++k) {
      Eigen::VectorXd tp = f.theta_hat, tm = f.theta_hat;
      tp(k) += h;
      tm(k) -= h;
      const Eigen::VectorXd gp = grad_analytic(ev, c.samp, tp);
      const Eigen::VectorXd gm = grad_analytic(ev, c.samp, tm);
      if (gp.size() != n || gm.size() != n) { ok = false; break; }
      H.col(k) = (gp - gm) / (2.0 * h);
    }
    if (ok) {
      H = 0.5 * (H + H.transpose()).eval();
      Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> es(H, Eigen::EigenvaluesOnly);
      const double lo = es.eigenvalues()(0);
      const double hi = es.eigenvalues()(n - 1);
      std::printf("       eig range [%.4e, %.4e]  condition number = %.3e\n",
                  lo, hi, hi / lo);
    } else {
      std::printf("       Hessian unavailable (non-PD Sigma near theta-hat)\n");
    }
  }

  // ---- Phase 6: constraint reparam is a no-op --------------------------
  std::printf("[P6] eq_groups=%zu  lin_constraint rows=%zu  unenforced=%s\n",
              c.pt.eq_groups.size(), c.pt.lin_constraint_d.size(),
              c.pt.has_unenforced_constraints ? "yes" : "no");
  CHECK(c.pt.lin_constraint_d.empty());
  CHECK_FALSE(c.pt.has_unenforced_constraints);

  std::printf("==============================================================\n");
}

}  // namespace

TEST_CASE("convergence diagnostics: bollen_democracy_sem") {
  run_diagnostics("bollen_democracy_sem");
}

TEST_CASE("convergence diagnostics: bfi_5factor") {
  run_diagnostics("bfi_5factor");
}
